# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:26:47+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity
from fastapi import Path, Query
from pydantic import constr

from models import (
    AccessibilityPreference,
    AccidentStatsYearGetResponse,
    BikePointGetResponse,
    BikePointSearchGetResponse,
    BikeProficiency,
    Categories,
    CyclePreference,
    Direction,
    Direction5,
    DisruptionIds,
    Ids,
    JourneyMetaModesGetResponse,
    JourneyPreference,
    LineIds,
    LineIdsArrivalsStopPointIdGetResponse,
    LineIdsDisruptionGetResponse,
    LineIdsGetResponse,
    LineIdsRouteGetResponse,
    LineIdsStatusGetResponse,
    LineIdsStatusStartDateToEndDateGetResponse,
    LineIdStopPointsGetResponse,
    LineMetaDisruptionCategoriesGetResponse,
    LineMetaModesGetResponse,
    LineMetaServiceTypesGetResponse,
    LineMetaSeverityGetResponse,
    LineModeModesDisruptionGetResponse,
    LineModeModesGetResponse,
    LineModeModesRouteGetResponse,
    LineModeModesStatusGetResponse,
    LineRouteGetResponse,
    Lines,
    LineStatusSeverityGetResponse,
    Mode,
    ModeActiveServiceTypesGetResponse,
    ModeModeArrivalsGetResponse,
    Modes,
    OccupancyBikePointsIdsGetResponse,
    OccupancyCarParkGetResponse,
    OccupancyChargeConnectorGetResponse,
    OccupancyChargeConnectorIdsGetResponse,
    PlaceGetResponse,
    PlaceIdGetResponse,
    PlaceMetaCategoriesGetResponse,
    PlaceMetaPlaceTypesGetResponse,
    PlaceSearchGetResponse,
    PlaceTypes,
    PlaceTypeTypesGetResponse,
    RoadGetResponse,
    RoadIdsDisruptionGetResponse,
    RoadIdsGetResponse,
    RoadIdsStatusGetResponse,
    RoadMetaCategoriesGetResponse,
    RoadMetaSeveritiesGetResponse,
    SearchMetaCategoriesGetResponse,
    SearchMetaSearchProvidersGetResponse,
    SearchMetaSortsGetResponse,
    ServiceTypes,
    ServiceTypes1,
    ServiceTypes2,
    ServiceTypes3,
    ServiceTypes4,
    ServiceTypes5,
    ServiceTypes6,
    Severities,
    StopPointIdArrivalDeparturesGetResponse,
    StopPointIdArrivalsGetResponse,
    StopPointIdCanReachOnLineLineIdGetResponse,
    StopPointIdCrowdingLineGetResponse,
    StopPointIdPlaceTypesGetResponse,
    StopPointIdRouteGetResponse,
    StopPointIdsDisruptionGetResponse,
    StopPointIdsGetResponse,
    StopPointMetaCategoriesGetResponse,
    StopPointMetaModesGetResponse,
    StopPointMetaStopTypesGetResponse,
    StopPointModeModesDisruptionGetResponse,
    StopPointServiceTypesGetResponse,
    StopPointStopPointIdCarParksGetResponse,
    StopPointStopPointIdTaxiRanksGetResponse,
    StopPointTypeTypesGetResponse,
    StopPointTypeTypesPagePageGetResponse,
    StopTypes,
    SystemObject,
    TflApiPresentationEntitiesCarParkOccupancy,
    TflApiPresentationEntitiesJourneyPlannerItineraryResult,
    TflApiPresentationEntitiesPlace,
    TflApiPresentationEntitiesRoadDisruption,
    TflApiPresentationEntitiesRouteSearchResponse,
    TflApiPresentationEntitiesRouteSequence,
    TflApiPresentationEntitiesSearchResponse,
    TflApiPresentationEntitiesStopPointsResponse,
    TflApiPresentationEntitiesTimetableResponse,
    TimeIs,
    Type1,
    Types,
    VehicleIdsArrivalsGetResponse,
    WalkingSpeed,
)

app = MCPProxy(
    description='Our unified API brings together data across all modes of transport into a single RESTful API. This API provides access to the most highly requested realtime and status infomation across all the modes of transport, in a single and consistent way. Access to the developer documentation is available at https://api.tfl.gov.uk',
    title='Transport for London Unified API',
    version='v1',
    servers=[{'url': 'https://api.digital.tfl.gov.uk'}],
)


@app.get('/AccidentStats/{year}', tags=['accident_statistics'])
def accident_stats__get(year: int):
    """
    Gets all accident details for accidents occuring in the specified year
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/AirQuality', tags=['environmental_monitoring'])
def air_quality__get():
    """
    Gets air quality data feed
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/BikePoint',
    tags=[
        'bike_point_data_management',
        'vehicle_occupancy_data',
        'location_data_management',
    ],
)
def bike_point__get_all():
    """
    Gets all bike point locations. The Place object has an addtionalProperties array which contains the nbBikes, nbDocks and nbSpaces
            numbers which give the status of the BikePoint. A mismatch in these numbers i.e. nbDocks - (nbBikes + nbSpaces) != 0 indicates broken docks.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/BikePoint/Search', tags=['bike_point_data_management', 'location_data_management']
)
def bike_point__search(query: str):
    """
    Search for bike stations by their name, a bike point's name often contains information about the name of the street
            or nearby landmarks, for example. Note that the search result does not contain the PlaceProperties i.e. the status
            or occupancy of the BikePoint, to get that information you should retrieve the BikePoint by its id on /BikePoint/id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/BikePoint/{id}',
    tags=[
        'bike_point_data_management',
        'location_data_management',
        'vehicle_occupancy_data',
    ],
)
def bike_point__get(id: str):
    """
    Gets the bike point with the given id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Cabwise/search', tags=['taxi_service_locator', 'location_data_management'])
def cabwise__get(
    lat: float,
    lon: float = ...,
    optype: Optional[str] = None,
    wc: Optional[str] = None,
    radius: Optional[float] = None,
    name: Optional[str] = None,
    max_results: Optional[int] = Query(None, alias='maxResults'),
    legacy_format: Optional[bool] = Query(None, alias='legacyFormat'),
    force_xml: Optional[bool] = Query(None, alias='forceXml'),
    twenty_four_seven_only: Optional[bool] = Query(None, alias='twentyFourSevenOnly'),
):
    """
    Gets taxis and minicabs contact information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Journey/JourneyResults/{from}/to/{to}', tags=['route_planning'])
def journey__journey_results(
    from_: str = Path(..., alias='from'),
    to: str = ...,
    via: Optional[str] = None,
    national_search: Optional[bool] = Query(None, alias='nationalSearch'),
    date: Optional[str] = None,
    time: Optional[str] = None,
    time_is: Optional[TimeIs] = Query(None, alias='timeIs'),
    journey_preference: Optional[JourneyPreference] = Query(
        None, alias='journeyPreference'
    ),
    mode: Optional[Mode] = None,
    accessibility_preference: Optional[AccessibilityPreference] = Query(
        None, alias='accessibilityPreference'
    ),
    from_name: Optional[str] = Query(None, alias='fromName'),
    to_name: Optional[str] = Query(None, alias='toName'),
    via_name: Optional[str] = Query(None, alias='viaName'),
    max_transfer_minutes: Optional[str] = Query(None, alias='maxTransferMinutes'),
    max_walking_minutes: Optional[str] = Query(None, alias='maxWalkingMinutes'),
    walking_speed: Optional[WalkingSpeed] = Query(None, alias='walkingSpeed'),
    cycle_preference: Optional[CyclePreference] = Query(None, alias='cyclePreference'),
    adjustment: Optional[str] = None,
    bike_proficiency: Optional[BikeProficiency] = Query(None, alias='bikeProficiency'),
    alternative_cycle: Optional[bool] = Query(None, alias='alternativeCycle'),
    alternative_walking: Optional[bool] = Query(None, alias='alternativeWalking'),
    apply_html_markup: Optional[bool] = Query(None, alias='applyHtmlMarkup'),
    use_multi_modal_call: Optional[bool] = Query(None, alias='useMultiModalCall'),
    walking_optimization: Optional[bool] = Query(None, alias='walkingOptimization'),
    taxi_only_trip: Optional[bool] = Query(None, alias='taxiOnlyTrip'),
    route_between_entrances: Optional[bool] = Query(
        None, alias='routeBetweenEntrances'
    ),
    use_real_time_live_arrivals: Optional[bool] = Query(
        None, alias='useRealTimeLiveArrivals'
    ),
    calc_one_direction: Optional[bool] = Query(None, alias='calcOneDirection'),
):
    """
    Perform a Journey Planner search from the parameters specified in simple types
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Journey/Meta/Modes', tags=['route_planning', 'public_transport_line_metadata']
)
def journey__meta():
    """
    Gets a list of all of the available journey planner modes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Meta/DisruptionCategories',
    tags=[
        'public_transport_line_metadata',
        'road_status_information',
        'stop_point_disruption_reporting',
    ],
)
def line__meta_disruption_categories():
    """
    Gets a list of valid disruption categories
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Meta/Modes',
    tags=['public_transport_line_metadata', 'stop_point_metadata_retrieval'],
)
def line__meta_modes():
    """
    Gets a list of valid modes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Meta/ServiceTypes',
    tags=['public_transport_line_metadata', 'line_route_control'],
)
def line__meta_service_types():
    """
    Gets a list of valid ServiceTypes to filter on
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Line/Meta/Severity', tags=['road_status_information'])
def line__meta_severity():
    """
    Gets a list of valid severity codes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Mode/{modes}',
    tags=[
        'public_transport_line_metadata',
        'stop_point_metadata_retrieval',
        'stop_point_information',
    ],
)
def line__get_by_mode(modes: Modes):
    """
    Gets lines that serve the given modes.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Mode/{modes}/Disruption',
    tags=['public_transport_line_metadata', 'stop_point_disruption_reporting'],
)
def line__disruption_by_mode(modes: Modes):
    """
    Get disruptions for all lines of the given modes.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Mode/{modes}/Route',
    tags=['route_planning', 'public_transport_line_metadata', 'line_route_control'],
)
def line__route_by_mode(
    modes: Modes,
    service_types: Optional[ServiceTypes] = Query(None, alias='serviceTypes'),
):
    """
    Gets all lines and their valid routes for given modes, including the name and id of the originating and terminating stops for each route
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Mode/{modes}/Status',
    tags=['public_transport_line_metadata', 'line_route_control'],
)
def line__status_by_mode(
    modes: Modes,
    detail: Optional[bool] = None,
    severity_level: Optional[str] = Query(None, alias='severityLevel'),
):
    """
    Gets the line status of for all lines for the given modes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Route',
    tags=['route_planning', 'public_transport_line_metadata', 'line_route_control'],
)
def line__route(
    service_types: Optional[ServiceTypes1] = Query(None, alias='serviceTypes')
):
    """
    Get all valid routes for all lines, including the name and id of the originating and terminating stops for each route.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Search/{query}',
    tags=['route_planning', 'public_transport_line_metadata', 'line_route_control'],
)
def line__search(
    query: str,
    modes: Optional[Modes] = None,
    service_types: Optional[ServiceTypes2] = Query(None, alias='serviceTypes'),
):
    """
    Search for lines or routes matching the query string
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/Status/{severity}',
    tags=[
        'public_transport_line_metadata',
        'line_route_control',
        'road_status_information',
    ],
)
def line__status_by_severity(severity: int):
    """
    Gets the line status for all lines with a given severity
            A list of valid severity codes can be obtained from a call to Line/Meta/Severity
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Line/{ids}', tags=['location_data_management', 'item_searching'])
def line__get(ids: Ids):
    """
    Gets lines that match the specified line ids.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/{ids}/Arrivals/{stopPointId}',
    tags=[
        'arrival_time_predictions',
        'stop_point_arrivals_departures',
        'line_route_control',
    ],
)
def line__arrivals(
    ids: Ids,
    stop_point_id: str = Path(..., alias='stopPointId'),
    direction: Optional[Direction] = None,
    destination_station_id: Optional[str] = Query(None, alias='destinationStationId'),
):
    """
    Get the list of arrival predictions for given line ids based at the given stop
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/{ids}/Disruption',
    tags=[
        'public_transport_line_metadata',
        'stop_point_disruption_reporting',
        'line_route_control',
    ],
)
def line__disruption(ids: Ids):
    """
    Get disruptions for the given line ids
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/{ids}/Route',
    tags=['route_planning', 'public_transport_line_metadata', 'line_route_control'],
)
def line__line_routes_by_ids(
    ids: Ids, service_types: Optional[ServiceTypes3] = Query(None, alias='serviceTypes')
):
    """
    Get all valid routes for given line ids, including the name and id of the originating and terminating stops for each route.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/{ids}/Status', tags=['public_transport_line_metadata', 'line_route_control']
)
def line__status_by_ids(ids: Ids, detail: Optional[bool] = None):
    """
    Gets the line status of for given line ids e.g Minor Delays
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/{ids}/Status/{StartDate}/to/{EndDate}',
    tags=['public_transport_line_metadata', 'line_route_control'],
)
def line__status(
    ids: Ids,
    detail: Optional[bool] = None,
    start_date: Union[str, str, str, str] = Query(..., alias='startDate'),
    end_date: Union[str, str, str, str] = Query(..., alias='endDate'),
    date_range_start_date: Optional[datetime] = Query(
        None, alias='dateRange.startDate'
    ),
    date_range_end_date: Optional[datetime] = Query(None, alias='dateRange.endDate'),
):
    """
    Gets the line status for given line ids during the provided dates e.g Minor Delays
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/{id}/Route/Sequence/{direction}',
    tags=['route_planning', 'public_transport_line_metadata', 'line_route_control'],
)
def line__route_sequence(
    id: str,
    direction: Direction = ...,
    service_types: Optional[ServiceTypes4] = Query(None, alias='serviceTypes'),
    exclude_crowding: Optional[bool] = Query(None, alias='excludeCrowding'),
):
    """
    Gets all valid routes for given line id, including the sequence of stops on each route.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/{id}/StopPoints',
    tags=[
        'public_transport_line_metadata',
        'stop_point_information',
        'specific_stop_point_data',
    ],
)
def line__stop_points(
    id: str,
    tfl_operated_national_rail_stations_only: Optional[bool] = Query(
        None, alias='tflOperatedNationalRailStationsOnly'
    ),
):
    """
    Gets a list of the stations that serve the given line id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/{id}/Timetable/{fromStopPointId}',
    tags=[
        'public_transport_line_metadata',
        'stop_point_information',
        'specific_stop_point_data',
        'stop_point_arrivals_departures',
    ],
)
def line__timetable(
    from_stop_point_id: str = Path(..., alias='fromStopPointId'), id: str = ...
):
    """
    Gets the timetable for a specified station on the give line
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Line/{id}/Timetable/{fromStopPointId}/to/{toStopPointId}',
    tags=[
        'route_planning',
        'public_transport_line_metadata',
        'stop_point_information',
        'stop_point_arrivals_departures',
    ],
)
def line__timetable_to(
    from_stop_point_id: str = Path(..., alias='fromStopPointId'),
    id: str = ...,
    to_stop_point_id: str = Path(..., alias='toStopPointId'),
):
    """
    Gets the timetable for a specified station on the give line with specified destination
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Mode/ActiveServiceTypes',
    tags=['public_transport_line_metadata', 'stop_point_metadata_retrieval'],
)
def mode__get_active_service_types():
    """
    Returns the service type active for a mode.
            Currently only supports tube
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Mode/{mode}/Arrivals',
    tags=[
        'arrival_time_predictions',
        'line_route_control',
        'stop_point_arrivals_departures',
    ],
)
def mode__arrivals(mode: str, count: Optional[int] = None):
    """
    Gets the next arrival predictions for all stops of a given mode
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Occupancy/BikePoints/{ids}',
    tags=['bike_point_data_management', 'vehicle_occupancy_data'],
)
def occupancy__get_bike_points_occupancies(ids: Ids):
    """
    Get the occupancy for bike points.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Occupancy/CarPark', tags=['vehicle_occupancy_data'])
def get__occupancy__car_park():
    """
    Gets the occupancy for all car parks that have occupancy data
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Occupancy/CarPark/{id}',
    tags=['vehicle_occupancy_data', 'location_data_management'],
)
def occupancy__get(id: str):
    """
    Gets the occupancy for a car park with a given id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Occupancy/ChargeConnector', tags=['vehicle_occupancy_data'])
def occupancy__get_all_charge_connector_status():
    """
    Gets the occupancy for all charge connectors
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Occupancy/ChargeConnector/{ids}',
    tags=['vehicle_occupancy_data', 'location_data_management'],
)
def occupancy__get_charge_connector_status(ids: Ids):
    """
    Gets the occupancy for a charge connectors with a given id (sourceSystemPlaceId)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Place', tags=['location_data_management', 'item_searching'])
def place__get_by_geo(
    radius: Optional[float] = None,
    categories: Optional[Categories] = None,
    include_children: Optional[bool] = Query(None, alias='includeChildren'),
    type: Optional[Type1] = None,
    active_only: Optional[bool] = Query(None, alias='activeOnly'),
    number_of_places_to_return: Optional[int] = Query(
        None, alias='numberOfPlacesToReturn'
    ),
    place_geo_sw_lat: Optional[float] = Query(None, alias='placeGeo.swLat'),
    place_geo_sw_lon: Optional[float] = Query(None, alias='placeGeo.swLon'),
    place_geo_ne_lat: Optional[float] = Query(None, alias='placeGeo.neLat'),
    place_geo_ne_lon: Optional[float] = Query(None, alias='placeGeo.neLon'),
    place_geo_lat: Optional[float] = Query(None, alias='placeGeo.lat'),
    place_geo_lon: Optional[float] = Query(None, alias='placeGeo.lon'),
):
    """
    Gets the places that lie within a geographic region. The geographic region of interest can either be specified
            by using a lat/lon geo-point and a radius in metres to return places within the locus defined by the lat/lon of
            its centre or alternatively, by the use of a bounding box defined by the lat/lon of its north-west and south-east corners.
            Optionally filters on type and can strip properties for a smaller payload.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Place/Address/Streets/{Postcode}', tags=['location_data_management'])
def place__get_streets_by_post_code(
    postcode: Union[str, str, str, str],
    postcode_input_postcode: Optional[
        constr(
            pattern=r'^(([gG][iI][rR] {0,}0[aA]{2})|((([a-pr-uwyzA-PR-UWYZ][a-hk-yA-HK-Y]?[0-9][0-9]?)|(([a-pr-uwyzA-PR-UWYZ][0-9][a-hjkstuwA-HJKSTUW])|([a-pr-uwyzA-PR-UWYZ][a-hk-yA-HK-Y][0-9][abehmnprv-yABEHMNPRV-Y]))) {0,}[0-9][abd-hjlnp-uw-zABD-HJLNP-UW-Z]{2}))$'
        )
    ] = Query(None, alias='postcodeInput.postcode'),
):
    """
    Gets the set of streets associated with a post code.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Place/Meta/Categories', tags=['location_data_management', 'item_searching'])
def place__meta_categories():
    """
    Gets a list of all of the available place property categories and keys.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Place/Meta/PlaceTypes', tags=['location_data_management', 'item_searching'])
def place__meta_place_types():
    """
    Gets a list of the available types of Place.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Place/Search', tags=['location_data_management', 'item_searching'])
def place__search(name: str, types: Optional[Types] = None):
    """
    Gets all places that matches the given query
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Place/Type/{types}', tags=['location_data_management'])
def place__get_by_type(
    types: Types, active_only: Optional[bool] = Query(None, alias='activeOnly')
):
    """
    Gets all places of a given type
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Place/{id}', tags=['location_data_management'])
def place__get(
    id: str, include_children: Optional[bool] = Query(None, alias='includeChildren')
):
    """
    Gets the place with the given id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Place/{type}/At/{Lat}/{Lon}', tags=['location_data_management'])
def place__get_at(
    type: Type1,
    lat: Union[str, str, str, str] = ...,
    lon: Union[str, str, str, str] = ...,
    location_lat: float = Query(..., alias='location.lat'),
    location_lon: float = Query(..., alias='location.lon'),
):
    """
    Gets any places of the given type whose geography intersects the given latitude and longitude. In practice this means the Place
            must be polygonal e.g. a BoroughBoundary.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Place/{type}/overlay/{z}/{Lat}/{Lon}/{width}/{height}',
    tags=['location_data_management', 'travel_time_comparison'],
)
def place__get_overlay(
    z: int,
    type: Type1 = ...,
    width: int = ...,
    height: int = ...,
    lat: Union[str, str, str, str] = ...,
    lon: Union[str, str, str, str] = ...,
    location_lat: float = Query(..., alias='location.lat'),
    location_lon: float = Query(..., alias='location.lon'),
):
    """
    Gets the place overlay for a given set of co-ordinates and a given width/height.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Road', tags=['road_status_information'])
def road__get():
    """
    Gets all roads managed by TfL
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Road/Meta/Categories',
    tags=['road_status_information', 'public_transport_line_metadata'],
)
def road__meta_categories():
    """
    Gets a list of valid RoadDisruption categories
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Road/Meta/Severities', tags=['road_status_information'])
def road__meta_severities():
    """
    Gets a list of valid RoadDisruption severity codes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Road/all/Disruption/{disruptionIds}',
    tags=['road_status_information', 'stop_point_disruption_reporting'],
)
def road__disruption_by_id(
    disruption_ids: DisruptionIds = Path(..., alias='disruptionIds'),
    strip_content: Optional[bool] = Query(None, alias='stripContent'),
):
    """
    Gets a list of active disruptions filtered by disruption Ids.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Road/all/Street/Disruption',
    tags=['road_status_information', 'stop_point_disruption_reporting'],
)
def road__disrupted_streets(
    start_date: datetime = Query(..., alias='startDate'),
    end_date: datetime = Query(..., alias='endDate'),
):
    """
    Gets a list of disrupted streets. If no date filters are provided, current disruptions are returned.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Road/{ids}', tags=['road_status_information', 'location_data_management'])
def get__road__ids(ids: Ids):
    """
    Gets the road with the specified id (e.g. A1)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Road/{ids}/Disruption',
    tags=['road_status_information', 'public_transport_line_metadata'],
)
def road__disruption(
    ids: Ids,
    strip_content: Optional[bool] = Query(None, alias='stripContent'),
    severities: Optional[Severities] = None,
    categories: Optional[Categories] = None,
    closures: Optional[bool] = None,
):
    """
    Get active disruptions, filtered by road ids
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Road/{ids}/Status', tags=['road_status_information'])
def road__status(
    ids: Ids,
    date_range_nullable_start_date: Optional[datetime] = Query(
        None, alias='dateRangeNullable.startDate'
    ),
    date_range_nullable_end_date: Optional[datetime] = Query(
        None, alias='dateRangeNullable.endDate'
    ),
):
    """
    Gets the specified roads with the status aggregated over the date range specified, or now until the end of today if no dates are passed.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Search', tags=['item_searching', 'location_data_management'])
def search__get(query: str):
    """
    Search the site for occurrences of the query string. The maximum number of results returned is equal to the maximum page size
            of 100. To return subsequent pages, use the paginated overload.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/Search/BusSchedules', tags=['item_searching', 'public_transport_line_metadata']
)
def search__bus_schedules(query: str):
    """
    Searches the bus schedules folder on S3 for a given bus number.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Search/Meta/Categories', tags=['item_searching', 'location_data_management'])
def search__meta_categories():
    """
    Gets the available search categories.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Search/Meta/SearchProviders', tags=['item_searching'])
def search__meta_search_providers():
    """
    Gets the available searchProvider names.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Search/Meta/Sorts', tags=['item_searching'])
def search__meta_sorts():
    """
    Gets the available sorting options.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint',
    tags=[
        'stop_point_information',
        'stop_point_metadata_retrieval',
        'specific_stop_point_data',
    ],
)
def stop_point__get_by_geo_point(
    stop_types: StopTypes = Query(..., alias='stopTypes'),
    radius: Optional[int] = None,
    use_stop_point_hierarchy: Optional[bool] = Query(
        None, alias='useStopPointHierarchy'
    ),
    modes: Optional[Modes] = None,
    categories: Optional[Categories] = None,
    return_lines: Optional[bool] = Query(None, alias='returnLines'),
    location_lat: float = Query(..., alias='location.lat'),
    location_lon: float = Query(..., alias='location.lon'),
):
    """
    Gets a list of StopPoints within {radius} by the specified criteria
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Meta/Categories',
    tags=['stop_point_information', 'stop_point_metadata_retrieval'],
)
def stop_point__meta_categories():
    """
    Gets the list of available StopPoint additional information categories
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Meta/Modes',
    tags=['stop_point_metadata_retrieval', 'stop_point_information'],
)
def stop_point__meta_modes():
    """
    Gets the list of available StopPoint modes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Meta/StopTypes',
    tags=['stop_point_metadata_retrieval', 'stop_point_information'],
)
def stop_point__meta_stop_types():
    """
    Gets the list of available StopPoint types
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Mode/{modes}',
    tags=[
        'stop_point_information',
        'stop_point_metadata_retrieval',
        'specific_stop_point_data',
    ],
)
def stop_point__get_by_mode(modes: Modes, page: Optional[int] = None):
    """
    Gets a list of StopPoints filtered by the modes available at that StopPoint.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Mode/{modes}/Disruption',
    tags=['public_transport_line_metadata', 'stop_point_disruption_reporting'],
)
def stop_point__disruption_by_mode(
    modes: Modes,
    include_route_blocked_stops: Optional[bool] = Query(
        None, alias='includeRouteBlockedStops'
    ),
):
    """
    Gets a distinct list of disrupted stop points for the given modes
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Search',
    tags=[
        'stop_point_information',
        'stop_point_metadata_retrieval',
        'specific_stop_point_data',
    ],
)
def get__stop_point__search(
    query: str,
    modes: Optional[Modes] = None,
    fares_only: Optional[bool] = Query(None, alias='faresOnly'),
    max_results: Optional[int] = Query(None, alias='maxResults'),
    lines: Optional[Lines] = None,
    include_hubs: Optional[bool] = Query(None, alias='includeHubs'),
    tfl_operated_national_rail_stations_only: Optional[bool] = Query(
        None, alias='tflOperatedNationalRailStationsOnly'
    ),
):
    """
    Search StopPoints by their common name, or their 5-digit Countdown Bus Stop Code.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Search/{query}',
    tags=[
        'stop_point_information',
        'specific_stop_point_data',
        'stop_point_metadata_retrieval',
    ],
)
def stop_point__search(
    query: str,
    modes: Optional[Modes] = None,
    fares_only: Optional[bool] = Query(None, alias='faresOnly'),
    max_results: Optional[int] = Query(None, alias='maxResults'),
    lines: Optional[Lines] = None,
    include_hubs: Optional[bool] = Query(None, alias='includeHubs'),
    tfl_operated_national_rail_stations_only: Optional[bool] = Query(
        None, alias='tflOperatedNationalRailStationsOnly'
    ),
):
    """
    Search StopPoints by their common name, or their 5-digit Countdown Bus Stop Code.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/ServiceTypes',
    tags=[
        'public_transport_line_metadata',
        'stop_point_metadata_retrieval',
        'specific_stop_point_data',
    ],
)
def stop_point__get_service_types(
    id: str,
    line_ids: Optional[LineIds] = Query(None, alias='lineIds'),
    modes: Optional[Modes] = None,
):
    """
    Gets the service types for a given stoppoint
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Sms/{id}',
    tags=[
        'stop_point_information',
        'specific_stop_point_data',
        'stop_point_metadata_retrieval',
    ],
)
def stop_point__get_by_sms(id: str, output: Optional[str] = None):
    """
    Gets a StopPoint for a given sms code.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Type/{types}',
    tags=['stop_point_information', 'stop_point_metadata_retrieval'],
)
def stop_point__get_by_type(types: Types):
    """
    Gets all stop points of a given type
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/Type/{types}/page/{page}',
    tags=[
        'stop_point_information',
        'stop_point_metadata_retrieval',
        'specific_stop_point_data',
    ],
)
def stop_point__get_by_type_with_pagination(types: Types, page: int = ...):
    """
    Gets all the stop points of given type(s) with a page number
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{ids}',
    tags=[
        'stop_point_information',
        'stop_point_metadata_retrieval',
        'specific_stop_point_data',
    ],
)
def stop_point__get(
    ids: Ids,
    include_crowding_data: Optional[bool] = Query(None, alias='includeCrowdingData'),
):
    """
    Gets a list of StopPoints corresponding to the given list of stop ids.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{ids}/Disruption',
    tags=[
        'stop_point_disruption_reporting',
        'stop_point_information',
        'public_transport_line_metadata',
    ],
)
def stop_point__disruption(
    ids: Ids,
    get_family: Optional[bool] = Query(None, alias='getFamily'),
    include_route_blocked_stops: Optional[bool] = Query(
        None, alias='includeRouteBlockedStops'
    ),
    flatten_response: Optional[bool] = Query(None, alias='flattenResponse'),
):
    """
    Gets all disruptions for the specified StopPointId, plus disruptions for any child Naptan records it may have.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{id}/ArrivalDepartures',
    tags=[
        'stop_point_arrivals_departures',
        'arrival_time_predictions',
        'specific_stop_point_data',
    ],
)
def stop_point__arrival_departures(
    id: str, line_ids: LineIds = Query(..., alias='lineIds')
):
    """
    Gets the list of arrival and departure predictions for the given stop point id (overground, Elizabeth line and thameslink only)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{id}/Arrivals',
    tags=['arrival_time_predictions', 'stop_point_arrivals_departures'],
)
def stop_point__arrivals(id: str):
    """
    Gets the list of arrival predictions for the given stop point id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{id}/CanReachOnLine/{lineId}',
    tags=[
        'stop_point_accessibility_analysis',
        'stop_point_information',
        'stop_point_metadata_retrieval',
    ],
)
def stop_point__reachable_from(
    id: str,
    line_id: str = Path(..., alias='lineId'),
    service_types: Optional[ServiceTypes5] = Query(None, alias='serviceTypes'),
):
    """
    Gets Stopoints that are reachable from a station/line combination.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{id}/Crowding/{line}',
    tags=[
        'public_transport_line_metadata',
        'stop_point_information',
        'specific_stop_point_data',
        'stop_point_disruption_reporting',
    ],
)
def stop_point__crowding(id: str, line: str = ..., direction: Direction = ...):
    """
    Gets all the Crowding data (static) for the StopPointId, plus crowding data for a given line and optionally a particular direction.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{id}/DirectionTo/{toStopPointId}',
    tags=[
        'public_transport_line_metadata',
        'line_route_control',
        'stop_point_information',
    ],
)
def stop_point__direction(
    id: str,
    to_stop_point_id: str = Path(..., alias='toStopPointId'),
    line_id: Optional[str] = Query(None, alias='lineId'),
):
    """
    Returns the canonical direction, "inbound" or "outbound", for a given pair of stop point Ids in the direction from -&gt; to.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{id}/Route',
    tags=[
        'public_transport_line_metadata',
        'stop_point_information',
        'specific_stop_point_data',
    ],
)
def stop_point__route(
    id: str, service_types: Optional[ServiceTypes6] = Query(None, alias='serviceTypes')
):
    """
    Returns the route sections for all the lines that service the given stop point ids
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{id}/placeTypes', tags=['location_data_management', 'item_searching']
)
def get__stop_point__id_place_types(
    id: str, place_types: PlaceTypes = Query(..., alias='placeTypes')
):
    """
    Get a list of places corresponding to a given id and place types.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{stopPointId}/CarParks',
    tags=[
        'location_data_management',
        'public_transport_line_metadata',
        'stop_point_information',
        'specific_stop_point_data',
    ],
)
def stop_point__get_car_parks_by_id(
    stop_point_id: str = Path(..., alias='stopPointId')
):
    """
    Get car parks corresponding to the given stop point id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/StopPoint/{stopPointId}/TaxiRanks',
    tags=['taxi_service_locator', 'stop_point_accessibility_analysis'],
)
def stop_point__get_taxi_ranks_by_ids(
    stop_point_id: str = Path(..., alias='stopPointId')
):
    """
    Gets a list of taxi ranks corresponding to the given stop point id.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/TravelTimes/compareOverlay/{z}/mapcenter/{mapCenterLat}/{mapCenterLon}/pinlocation/{pinLat}/{pinLon}/dimensions/{width}/{height}',
    tags=['travel_time_comparison', 'route_planning'],
)
def travel_time__get_compare_overlay(
    z: int,
    pin_lat: float = Path(..., alias='pinLat'),
    pin_lon: float = Path(..., alias='pinLon'),
    map_center_lat: float = Path(..., alias='mapCenterLat'),
    map_center_lon: float = Path(..., alias='mapCenterLon'),
    scenario_title: str = Query(..., alias='scenarioTitle'),
    time_of_day_id: str = Query(..., alias='timeOfDayId'),
    mode_id: str = Query(..., alias='modeId'),
    width: int = ...,
    height: int = ...,
    direction: Direction5 = ...,
    travel_time_interval: int = Query(..., alias='travelTimeInterval'),
    compare_type: str = Query(..., alias='compareType'),
    compare_value: str = Query(..., alias='compareValue'),
):
    """
    Gets the TravelTime overlay.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/TravelTimes/overlay/{z}/mapcenter/{mapCenterLat}/{mapCenterLon}/pinlocation/{pinLat}/{pinLon}/dimensions/{width}/{height}',
    tags=['travel_time_comparison', 'route_planning'],
)
def travel_time__get_overlay(
    z: int,
    pin_lat: float = Path(..., alias='pinLat'),
    pin_lon: float = Path(..., alias='pinLon'),
    map_center_lat: float = Path(..., alias='mapCenterLat'),
    map_center_lon: float = Path(..., alias='mapCenterLon'),
    scenario_title: str = Query(..., alias='scenarioTitle'),
    time_of_day_id: str = Query(..., alias='timeOfDayId'),
    mode_id: str = Query(..., alias='modeId'),
    width: int = ...,
    height: int = ...,
    direction: Direction5 = ...,
    travel_time_interval: int = Query(..., alias='travelTimeInterval'),
):
    """
    Gets the TravelTime overlay.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/Vehicle/{ids}/Arrivals', tags=['vehicle_arrival_prediction'])
def vehicle__get(ids: Ids):
    """
    Gets the predictions for a given list of vehicle Id's.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
