# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:26:47+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel, constr


class SystemDataSpatialDbGeographyWellKnownValue(BaseModel):
    coordinateSystemId: Optional[int] = None
    wellKnownBinary: Optional[str] = None
    wellKnownText: Optional[str] = None


class SystemObject(BaseModel):
    pass


class TflApiCommonApiVersionInfo(BaseModel):
    assemblies: Optional[List[str]] = None
    label: Optional[str] = None
    timestamp: Optional[datetime] = None
    version: Optional[str] = None


class TflApiCommonDateRange(BaseModel):
    endDate: Optional[datetime] = None
    startDate: Optional[datetime] = None


class TflApiCommonDateRangeNullable(BaseModel):
    endDate: Optional[datetime] = None
    startDate: Optional[datetime] = None


class TflApiCommonGeoPoint(BaseModel):
    lat: float
    lon: float


class TflApiCommonJourneyPlannerJpElevation(BaseModel):
    distance: Optional[int] = None
    endLat: Optional[float] = None
    endLon: Optional[float] = None
    gradient: Optional[float] = None
    heightFromPreviousPoint: Optional[int] = None
    startLat: Optional[float] = None
    startLon: Optional[float] = None


class TflApiCommonPlaceGeo(BaseModel):
    lat: Optional[float] = None
    lon: Optional[float] = None
    neLat: Optional[float] = None
    neLon: Optional[float] = None
    swLat: Optional[float] = None
    swLon: Optional[float] = None


class TflApiCommonPostcodeInput(BaseModel):
    postcode: Optional[
        constr(
            pattern=r'^(([gG][iI][rR] {0,}0[aA]{2})|((([a-pr-uwyzA-PR-UWYZ][a-hk-yA-HK-Y]?[0-9][0-9]?)|(([a-pr-uwyzA-PR-UWYZ][0-9][a-hjkstuwA-HJKSTUW])|([a-pr-uwyzA-PR-UWYZ][a-hk-yA-HK-Y][0-9][abehmnprv-yABEHMNPRV-Y]))) {0,}[0-9][abd-hjlnp-uw-zABD-HJLNP-UW-Z]{2}))$'
        )
    ] = None


class TflApiPresentationEntitiesAccidentStatsAccidentStatsOrderedSummary(BaseModel):
    accidents: Optional[int] = None
    borough: Optional[str] = None
    year: Optional[int] = None


class TflApiPresentationEntitiesAccidentStatsCasualty(BaseModel):
    age: Optional[int] = None
    ageBand: Optional[str] = None
    class_: Optional[str] = Field(None, alias='class')
    mode: Optional[str] = None
    severity: Optional[str] = None


class TflApiPresentationEntitiesAccidentStatsVehicle(BaseModel):
    type: Optional[str] = None


class TflApiPresentationEntitiesActiveServiceType(BaseModel):
    mode: Optional[str] = None
    serviceType: Optional[str] = None


class TflApiPresentationEntitiesAdditionalProperties(BaseModel):
    category: Optional[str] = None
    key: Optional[str] = None
    modified: Optional[datetime] = None
    sourceSystemKey: Optional[str] = None
    value: Optional[str] = None


class DepartureStatus(Enum):
    OnTime = 'OnTime'
    Delayed = 'Delayed'
    Cancelled = 'Cancelled'
    NotStoppingAtStation = 'NotStoppingAtStation'


class TflApiPresentationEntitiesBay(BaseModel):
    bayCount: Optional[int] = None
    bayType: Optional[str] = None
    free: Optional[int] = None
    occupied: Optional[int] = None


class TflApiPresentationEntitiesBikePointOccupancy(BaseModel):
    bikesCount: Optional[int] = Field(None, description='Total bike counts')
    eBikesCount: Optional[int] = Field(None, description='Total ebikes count')
    emptyDocks: Optional[int] = Field(None, description='Empty docks')
    id: Optional[str] = Field(
        None, description='Id of the bike point such as BikePoints_1'
    )
    name: Optional[str] = Field(
        None, description='Name / Common name of the bike point'
    )
    standardBikesCount: Optional[int] = Field(
        None, description='Total standard bikes count'
    )
    totalDocks: Optional[int] = Field(None, description='Total docks available')


class TflApiPresentationEntitiesCarParkOccupancy(BaseModel):
    bays: Optional[List[TflApiPresentationEntitiesBay]] = None
    carParkDetailsUrl: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None


class TflApiPresentationEntitiesChargeConnectorOccupancy(BaseModel):
    id: Optional[int] = Field(None, description='')
    sourceSystemPlaceId: Optional[str] = Field(None, description='')
    status: Optional[str] = Field(None, description='')


class TflApiPresentationEntitiesCoordinate(BaseModel):
    easting: Optional[float] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    northing: Optional[float] = None
    xCoord: Optional[int] = None
    yCoord: Optional[int] = None


class RouteType(Enum):
    Unknown = 'Unknown'
    All = 'All'
    Cycle_Superhighways = 'Cycle Superhighways'
    Quietways = 'Quietways'
    Cycleways = 'Cycleways'
    Mini_Hollands = 'Mini-Hollands'
    Central_London_Grid = 'Central London Grid'
    Streetspace_Route = 'Streetspace Route'


class Status(Enum):
    Unknown = 'Unknown'
    All = 'All'
    Open = 'Open'
    In_Progress = 'In Progress'
    Planned = 'Planned'
    Planned___Subject_to_feasibility_and_consultation_ = (
        'Planned - Subject to feasibility and consultation.'
    )
    Not_Open = 'Not Open'


class TflApiPresentationEntitiesDisruptedPoint(BaseModel):
    additionalInformation: Optional[str] = None
    appearance: Optional[str] = None
    atcoCode: Optional[str] = None
    commonName: Optional[str] = None
    description: Optional[str] = None
    fromDate: Optional[datetime] = None
    mode: Optional[str] = None
    stationAtcoCode: Optional[str] = None
    toDate: Optional[datetime] = None
    type: Optional[str] = None


class Category(Enum):
    Undefined = 'Undefined'
    RealTime = 'RealTime'
    PlannedWork = 'PlannedWork'
    Information = 'Information'
    Event = 'Event'
    Crowding = 'Crowding'
    StatusAlert = 'StatusAlert'


class TflApiPresentationEntitiesFaresFare(BaseModel):
    cap: Optional[float] = None
    cost: Optional[str] = None
    description: Optional[str] = None
    id: Optional[int] = None
    mode: Optional[str] = None
    passengerType: Optional[str] = None
    ticketTime: Optional[str] = None
    ticketType: Optional[str] = None
    validFrom: Optional[datetime] = None
    validUntil: Optional[datetime] = None
    zone: Optional[str] = None


class FareCategory(Enum):
    Cash = 'Cash'
    Oyster = 'Oyster'
    Contactless = 'Contactless'
    ContactlessOnly = 'ContactlessOnly'
    All = 'All'


class TflApiPresentationEntitiesFaresFareStation(BaseModel):
    atcoCode: Optional[str] = None
    commonName: Optional[str] = None
    fareCategory: Optional[FareCategory] = None


class TflApiPresentationEntitiesFaresFaresMode(BaseModel):
    description: Optional[str] = None
    id: Optional[int] = None
    name: Optional[str] = None


class TflApiPresentationEntitiesFaresFaresPeriod(BaseModel):
    endDate: Optional[datetime] = None
    id: Optional[int] = None
    isFuture: Optional[bool] = None
    startDate: Optional[datetime] = None
    viewableDate: Optional[datetime] = None


class TflApiPresentationEntitiesFaresJourney(BaseModel):
    fromStation: Optional[TflApiPresentationEntitiesFaresFareStation] = None
    toStation: Optional[TflApiPresentationEntitiesFaresFareStation] = None


class TflApiPresentationEntitiesFaresPassengerType(BaseModel):
    description: Optional[str] = None
    displayName: Optional[str] = None
    displayOrder: Optional[int] = None
    type: Optional[str] = None


class TflApiPresentationEntitiesFaresTicketTime(BaseModel):
    description: Optional[str] = None
    type: Optional[str] = None


class TflApiPresentationEntitiesFaresTicketType(BaseModel):
    description: Optional[str] = None
    type: Optional[str] = None


class TflApiPresentationEntitiesGeoCodeSearchMatch(BaseModel):
    address: Optional[str] = Field(
        None,
        description="A string describing the formatted address of the place. Adds additional context to the place's Name.",
    )
    id: Optional[str] = None
    lat: Optional[float] = None
    lon: Optional[float] = None
    name: Optional[str] = None
    types: Optional[List[str]] = Field(
        None, description='The type of the place e.g. "street_address"'
    )
    url: Optional[str] = None


class SkyDirectionDescription(Enum):
    North = 'North'
    NorthEast = 'NorthEast'
    East = 'East'
    SouthEast = 'SouthEast'
    South = 'South'
    SouthWest = 'SouthWest'
    West = 'West'
    NorthWest = 'NorthWest'


class TrackType(Enum):
    CycleSuperHighway = 'CycleSuperHighway'
    CanalTowpath = 'CanalTowpath'
    QuietRoad = 'QuietRoad'
    ProvisionForCyclists = 'ProvisionForCyclists'
    BusyRoads = 'BusyRoads'
    None_ = 'None'
    PushBike = 'PushBike'
    Quietway = 'Quietway'


class TflApiPresentationEntitiesInterval(BaseModel):
    stopId: Optional[str] = None
    timeToArrival: Optional[float] = None


class TflApiPresentationEntitiesJourneyPlannerFareCaveat(BaseModel):
    text: Optional[str] = None
    type: Optional[str] = None


class TflApiPresentationEntitiesJourneyPlannerFareTapDetails(BaseModel):
    busRouteId: Optional[str] = None
    hostDeviceType: Optional[str] = None
    modeType: Optional[str] = None
    nationalLocationCode: Optional[int] = None
    tapTimestamp: Optional[datetime] = None
    validationType: Optional[str] = None


class TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData(
    BaseModel
):
    destinationId: Optional[str] = None
    destinationNumberOfBikes: Optional[int] = None
    destinationNumberOfEmptySlots: Optional[int] = None
    originId: Optional[str] = None
    originNumberOfBikes: Optional[int] = None
    originNumberOfEmptySlots: Optional[int] = None


class TflApiPresentationEntitiesJourneyPlannerJourneyVector(BaseModel):
    from_: Optional[str] = Field(None, alias='from')
    to: Optional[str] = None
    uri: Optional[str] = None
    via: Optional[str] = None


class TflApiPresentationEntitiesJourneyPlannerObstacle(BaseModel):
    incline: Optional[str] = None
    position: Optional[str] = None
    stopId: Optional[int] = None
    type: Optional[str] = None


class TflApiPresentationEntitiesJourneyPlannerPlannedWork(BaseModel):
    createdDateTime: Optional[datetime] = None
    description: Optional[str] = None
    id: Optional[str] = None
    lastUpdateDateTime: Optional[datetime] = None


class DateTimeType(Enum):
    Arriving = 'Arriving'
    Departing = 'Departing'


class TflApiPresentationEntitiesJourneyPlannerTimeAdjustment(BaseModel):
    date: Optional[str] = None
    time: Optional[str] = None
    timeIs: Optional[str] = None
    uri: Optional[str] = None


class TflApiPresentationEntitiesJourneyPlannerTimeAdjustments(BaseModel):
    earlier: Optional[TflApiPresentationEntitiesJourneyPlannerTimeAdjustment] = None
    earliest: Optional[TflApiPresentationEntitiesJourneyPlannerTimeAdjustment] = None
    later: Optional[TflApiPresentationEntitiesJourneyPlannerTimeAdjustment] = None
    latest: Optional[TflApiPresentationEntitiesJourneyPlannerTimeAdjustment] = None


class TflApiPresentationEntitiesKnownJourney(BaseModel):
    hour: Optional[str] = None
    intervalId: Optional[int] = None
    minute: Optional[str] = None


class TflApiPresentationEntitiesLineGroup(BaseModel):
    lineIdentifier: Optional[List[str]] = None
    naptanIdReference: Optional[str] = None
    stationAtcoCode: Optional[str] = None


class TflApiPresentationEntitiesLineModeGroup(BaseModel):
    lineIdentifier: Optional[List[str]] = None
    modeName: Optional[str] = None


class TflApiPresentationEntitiesLineRouteSection(BaseModel):
    destination: Optional[str] = None
    direction: Optional[str] = None
    fromStation: Optional[str] = None
    routeId: Optional[int] = None
    serviceType: Optional[str] = None
    toStation: Optional[str] = None
    vehicleDestinationText: Optional[str] = None


class TflApiPresentationEntitiesLineServiceTypeInfo(BaseModel):
    name: Optional[str] = None
    uri: Optional[str] = None


class TflApiPresentationEntitiesLineSpecificServiceType(BaseModel):
    serviceType: Optional[TflApiPresentationEntitiesLineServiceTypeInfo] = None
    stopServesServiceType: Optional[bool] = None


class TflApiPresentationEntitiesMatchedRoute(BaseModel):
    destination: Optional[str] = Field(
        None, description='The Id (NaPTAN code) or the Destination StopPoint'
    )
    destinationName: Optional[str] = Field(
        None, description='The name of the Destination StopPoint'
    )
    direction: Optional[str] = Field(None, description='Inbound or Outbound')
    name: Optional[str] = Field(None, description='Name such as "72"')
    originationName: Optional[str] = Field(
        None, description='The name of the Origin StopPoint'
    )
    originator: Optional[str] = Field(
        None, description='The Id (NaPTAN code) of the Origin StopPoint'
    )
    routeCode: Optional[str] = Field(None, description='The route code')
    serviceType: Optional[str] = Field(None, description='Regular or Night')
    validFrom: Optional[datetime] = Field(
        None,
        description='The DateTime that the Service containing this Route is valid from.',
    )
    validTo: Optional[datetime] = Field(
        None,
        description='The DateTime that the Service containing this Route is valid until.',
    )


class TflApiPresentationEntitiesMatchedRouteSections(BaseModel):
    id: Optional[int] = None


class TflApiPresentationEntitiesMessage(BaseModel):
    bulletOrder: Optional[int] = None
    header: Optional[bool] = None
    linkText: Optional[str] = None
    messageText: Optional[str] = None
    url: Optional[str] = None


class TflApiPresentationEntitiesMode(BaseModel):
    isFarePaying: Optional[bool] = None
    isScheduledService: Optional[bool] = None
    isTflService: Optional[bool] = None
    modeName: Optional[str] = None
    motType: Optional[str] = None
    network: Optional[str] = None


class TflApiPresentationEntitiesNetworkStatus(BaseModel):
    message: Optional[str] = None
    operator: Optional[str] = None
    status: Optional[str] = None
    statusLevel: Optional[int] = None


class TflApiPresentationEntitiesOrderedRoute(BaseModel):
    name: Optional[str] = None
    naptanIds: Optional[List[str]] = None
    serviceType: Optional[str] = None


class TflApiPresentationEntitiesPassengerFlow(BaseModel):
    timeSlice: Optional[str] = Field(
        None,
        description='Time in 24hr format with 15 minute intervals e.g. 0500-0515, 0515-0530 etc.',
    )
    value: Optional[int] = Field(
        None, description='Count of passenger flow towards a platform'
    )


class TflApiPresentationEntitiesPathAttribute(BaseModel):
    name: Optional[str] = None
    value: Optional[str] = None


class Type(Enum):
    Normal = 'Normal'
    FrequencyHours = 'FrequencyHours'
    FrequencyMinutes = 'FrequencyMinutes'
    Unknown = 'Unknown'


class TflApiPresentationEntitiesPlace(BaseModel):
    additionalProperties: Optional[
        List[TflApiPresentationEntitiesAdditionalProperties]
    ] = Field(
        None,
        description='A bag of additional key/value pairs with extra information about this place.',
    )
    children: Optional[List[TflApiPresentationEntitiesPlace]] = None
    childrenUrls: Optional[List[str]] = None
    commonName: Optional[str] = Field(None, description='A human readable name.')
    distance: Optional[float] = Field(
        None,
        description='The distance of the place from its search point, if this is the result\r\n            of a geographical search, otherwise zero.',
    )
    id: Optional[str] = Field(None, description='A unique identifier.')
    lat: Optional[float] = Field(None, description='WGS84 latitude of the location.')
    lon: Optional[float] = Field(None, description='WGS84 longitude of the location.')
    placeType: Optional[str] = Field(
        None,
        description='The type of Place. See /Place/Meta/placeTypes for possible values.',
    )
    url: Optional[str] = Field(
        None, description='The unique location of this resource.'
    )


class TflApiPresentationEntitiesPlaceCategory(BaseModel):
    availableKeys: Optional[List[str]] = None
    category: Optional[str] = None


class TflApiPresentationEntitiesPlacePolygon(BaseModel):
    commonName: Optional[str] = None
    geoPoints: Optional[List[TflApiCommonGeoPoint]] = None


class TflApiPresentationEntitiesPoint(BaseModel):
    lat: Optional[float] = Field(None, description='WGS84 latitude of the location.')
    lon: Optional[float] = Field(None, description='WGS84 longitude of the location.')


class TflApiPresentationEntitiesPredictionTiming(BaseModel):
    countdownServerAdjustment: Optional[str] = None
    insert: Optional[datetime] = None
    read: Optional[datetime] = None
    received: Optional[datetime] = None
    sent: Optional[datetime] = None
    source: Optional[datetime] = None


class TflApiPresentationEntitiesRedirect(BaseModel):
    active: Optional[bool] = None
    longUrl: Optional[str] = None
    shortUrl: Optional[str] = None


class TflApiPresentationEntitiesRoadCorridor(BaseModel):
    bounds: Optional[str] = Field(
        None,
        description='The Bounds of the Corridor, given by the south-east followed by the north-west co-ordinate\r\n            pair in geoJSON format e.g. "[[-1.241531,51.242151],[1.641223,53.765721]]"',
    )
    displayName: Optional[str] = Field(
        None,
        description='The display name of the Corridor e.g. "North Circular (A406)". This\r\n            may be identical to the Id.',
    )
    envelope: Optional[str] = Field(
        None,
        description='The Envelope of the Corridor, given by the corner co-ordinates of a rectangular (four-point) polygon\r\n            in geoJSON format e.g. "[[-1.241531,51.242151],[-1.241531,53.765721],[1.641223,53.765721],[1.641223,51.242151]]"',
    )
    group: Optional[str] = Field(
        None,
        description='The group name of the Corridor e.g. "Central London". Most corridors are not grouped, in which case this field can be null.',
    )
    id: Optional[str] = Field(None, description='The Id of the Corridor e.g. "A406"')
    statusAggregationEndDate: Optional[datetime] = Field(
        None,
        description='The end of the period over which status has been aggregated, or null if this is the current corridor status.',
    )
    statusAggregationStartDate: Optional[datetime] = Field(
        None,
        description='The start of the period over which status has been aggregated, or null if this is the current corridor status.',
    )
    statusSeverity: Optional[str] = Field(
        None, description='Standard multi-mode status severity code'
    )
    statusSeverityDescription: Optional[str] = Field(
        None,
        description='Description of the status severity as applied to RoadCorridors',
    )
    url: Optional[str] = Field(None, description='URL to retrieve this Corridor.')


class TflApiPresentationEntitiesRoadDisruptionSchedule(BaseModel):
    endTime: Optional[datetime] = None
    startTime: Optional[datetime] = None


class Phase(Enum):
    Unscoped = 'Unscoped'
    Concept = 'Concept'
    ConsultationEnded = 'ConsultationEnded'
    Consultation = 'Consultation'
    Construction = 'Construction'
    Complete = 'Complete'


class TflApiPresentationEntitiesRoadProject(BaseModel):
    boroughsBenefited: Optional[List[str]] = None
    constructionEndDate: Optional[datetime] = None
    constructionStartDate: Optional[datetime] = None
    consultationEndDate: Optional[datetime] = None
    consultationPageUrl: Optional[str] = None
    consultationStartDate: Optional[datetime] = None
    contactEmail: Optional[str] = None
    contactName: Optional[str] = None
    cycleSuperhighwayId: Optional[str] = None
    externalPageUrl: Optional[str] = None
    phase: Optional[Phase] = None
    projectDescription: Optional[str] = None
    projectId: Optional[str] = None
    projectName: Optional[str] = None
    projectPageUrl: Optional[str] = None
    projectSummaryPageUrl: Optional[str] = None
    schemeName: Optional[str] = None


class TflApiPresentationEntitiesSearchMatch(BaseModel):
    id: Optional[str] = None
    lat: Optional[float] = None
    lon: Optional[float] = None
    name: Optional[str] = None
    url: Optional[str] = None


class TflApiPresentationEntitiesSearchResponse(BaseModel):
    from_: Optional[int] = Field(None, alias='from')
    matches: Optional[List[TflApiPresentationEntitiesSearchMatch]] = None
    maxScore: Optional[float] = None
    page: Optional[int] = None
    pageSize: Optional[int] = None
    provider: Optional[str] = None
    query: Optional[str] = None
    total: Optional[int] = None


class TflApiPresentationEntitiesServiceFrequency(BaseModel):
    highestFrequency: Optional[float] = None
    lowestFrequency: Optional[float] = None


class TflApiPresentationEntitiesStationInterval(BaseModel):
    id: Optional[str] = None
    intervals: Optional[List[TflApiPresentationEntitiesInterval]] = None


class TflApiPresentationEntitiesStatusSeverity(BaseModel):
    description: Optional[str] = None
    modeName: Optional[str] = None
    severityLevel: Optional[int] = None


class TflApiPresentationEntitiesStopPointCategory(BaseModel):
    availableKeys: Optional[List[str]] = None
    category: Optional[str] = None


class TflApiPresentationEntitiesStopPointRouteSection(BaseModel):
    destinationName: Optional[str] = None
    direction: Optional[str] = None
    isActive: Optional[bool] = None
    lineId: Optional[str] = None
    lineString: Optional[str] = None
    mode: Optional[str] = None
    naptanId: Optional[str] = None
    routeSectionName: Optional[str] = None
    serviceType: Optional[str] = None
    validFrom: Optional[datetime] = None
    validTo: Optional[datetime] = None
    vehicleDestinationText: Optional[str] = None


class ServiceType(Enum):
    Regular = 'Regular'
    Night = 'Night'


class TflApiPresentationEntitiesStreetSegment(BaseModel):
    lineString: Optional[str] = Field(
        None,
        description='geoJSON formatted LineString containing two latitude/longitude (WGS84) pairs that identify the start and end points of the street segment.',
    )
    sourceSystemId: Optional[int] = Field(
        None,
        description='The ID from the source system of the disruption that this street belongs to.',
    )
    sourceSystemKey: Optional[str] = Field(
        None,
        description='The key of the source system of the disruption that this street belongs to.',
    )
    toid: Optional[str] = Field(
        None,
        description='A 16 digit unique integer identifying a OS ITN (Ordnance Survey Integrated Transport Network) road link.',
    )


class TflApiPresentationEntitiesTimetablesDisambiguationOption(BaseModel):
    description: Optional[str] = None
    uri: Optional[str] = None


class TflApiPresentationEntitiesTrainLoading(BaseModel):
    direction: Optional[str] = Field(
        None,
        description='Direction in regards to Journey Planner i.e. inbound or outbound',
    )
    line: Optional[str] = Field(None, description='The Line Name e.g. "Victoria"')
    lineDirection: Optional[str] = Field(
        None, description='Direction of the Line e.g. NB, SB, WB etc.'
    )
    naptanTo: Optional[str] = Field(None, description='Naptan of the adjacent station')
    platformDirection: Optional[str] = Field(
        None, description='Direction displayed on the platform e.g. NB, SB, WB etc.'
    )
    timeSlice: Optional[str] = Field(
        None,
        description='Time in 24hr format with 15 minute intervals e.g. 0500-0515, 0515-0530 etc.',
    )
    value: Optional[int] = Field(
        None,
        description='Scale between 1-6, \r\n             1 = Very quiet, 2 = Quiet, 3 = Fairly busy, 4 = Busy, 5 = Very busy, 6 = Exceptionally busy',
    )


class TflApiPresentationEntitiesTwentyFourHourClockTime(BaseModel):
    hour: Optional[str] = None
    minute: Optional[str] = None


class TflApiPresentationEntitiesValidityPeriod(BaseModel):
    fromDate: Optional[datetime] = Field(
        None, description='Gets or sets the start date.'
    )
    isNow: Optional[bool] = Field(
        None, description='If true is a realtime status rather than planned or info'
    )
    toDate: Optional[datetime] = Field(None, description='Gets or sets the end date.')


class BikePointGetResponse(RootModel[List[TflApiPresentationEntitiesPlace]]):
    root: List[TflApiPresentationEntitiesPlace]


class BikePointSearchGetResponse(RootModel[List[TflApiPresentationEntitiesPlace]]):
    root: List[TflApiPresentationEntitiesPlace]


class TimeIs(Enum):
    Arriving = 'Arriving'
    Departing = 'Departing'


class JourneyPreference(Enum):
    LeastInterchange = 'LeastInterchange'
    LeastTime = 'LeastTime'
    LeastWalking = 'LeastWalking'


class AccessibilityPreferenceEnum(Enum):
    NoRequirements = 'NoRequirements'
    NoSolidStairs = 'NoSolidStairs'
    NoEscalators = 'NoEscalators'
    NoElevators = 'NoElevators'
    StepFreeToVehicle = 'StepFreeToVehicle'
    StepFreeToPlatform = 'StepFreeToPlatform'


class WalkingSpeed(Enum):
    Slow = 'Slow'
    Average = 'Average'
    Fast = 'Fast'


class CyclePreference(Enum):
    None_ = 'None'
    LeaveAtStation = 'LeaveAtStation'
    TakeOnTransport = 'TakeOnTransport'
    AllTheWay = 'AllTheWay'
    CycleHire = 'CycleHire'


class BikeProficiencyEnum(Enum):
    Easy = 'Easy'
    Moderate = 'Moderate'
    Fast = 'Fast'


class Mode(RootModel[List[str]]):
    root: List[str]


class AccessibilityPreference(RootModel[List[AccessibilityPreferenceEnum]]):
    root: List[AccessibilityPreferenceEnum]


class BikeProficiency(RootModel[List[BikeProficiencyEnum]]):
    root: List[BikeProficiencyEnum]


class JourneyMetaModesGetResponse(RootModel[List[TflApiPresentationEntitiesMode]]):
    root: List[TflApiPresentationEntitiesMode]


class LineMetaDisruptionCategoriesGetResponse(RootModel[List[str]]):
    root: List[str]


class LineMetaModesGetResponse(RootModel[List[TflApiPresentationEntitiesMode]]):
    root: List[TflApiPresentationEntitiesMode]


class LineMetaServiceTypesGetResponse(RootModel[List[str]]):
    root: List[str]


class LineMetaSeverityGetResponse(
    RootModel[List[TflApiPresentationEntitiesStatusSeverity]]
):
    root: List[TflApiPresentationEntitiesStatusSeverity]


class Modes(RootModel[List[str]]):
    root: List[str]


class ServiceTypes(RootModel[List[ServiceType]]):
    root: List[ServiceType]


class ServiceTypes1(RootModel[List[ServiceType]]):
    root: List[ServiceType]


class ServiceTypes2(RootModel[List[ServiceType]]):
    root: List[ServiceType]


class Ids(RootModel[List[str]]):
    root: List[str]


class Direction(Enum):
    inbound = 'inbound'
    outbound = 'outbound'
    all = 'all'


class ServiceTypes3(RootModel[List[ServiceType]]):
    root: List[ServiceType]


class ServiceTypes4(RootModel[List[ServiceType]]):
    root: List[ServiceType]


class ModeActiveServiceTypesGetResponse(
    RootModel[List[TflApiPresentationEntitiesActiveServiceType]]
):
    root: List[TflApiPresentationEntitiesActiveServiceType]


class OccupancyBikePointsIdsGetResponse(
    RootModel[List[TflApiPresentationEntitiesBikePointOccupancy]]
):
    root: List[TflApiPresentationEntitiesBikePointOccupancy]


class OccupancyCarParkGetResponse(
    RootModel[List[TflApiPresentationEntitiesCarParkOccupancy]]
):
    root: List[TflApiPresentationEntitiesCarParkOccupancy]


class OccupancyChargeConnectorGetResponse(
    RootModel[List[TflApiPresentationEntitiesChargeConnectorOccupancy]]
):
    root: List[TflApiPresentationEntitiesChargeConnectorOccupancy]


class OccupancyChargeConnectorIdsGetResponse(
    RootModel[List[TflApiPresentationEntitiesChargeConnectorOccupancy]]
):
    root: List[TflApiPresentationEntitiesChargeConnectorOccupancy]


class Categories(RootModel[List[str]]):
    root: List[str]


class Type1(RootModel[List[str]]):
    root: List[str]


class PlaceMetaCategoriesGetResponse(
    RootModel[List[TflApiPresentationEntitiesPlaceCategory]]
):
    root: List[TflApiPresentationEntitiesPlaceCategory]


class PlaceMetaPlaceTypesGetResponse(
    RootModel[List[TflApiPresentationEntitiesPlaceCategory]]
):
    root: List[TflApiPresentationEntitiesPlaceCategory]


class PlaceSearchGetResponse(RootModel[List[TflApiPresentationEntitiesPlace]]):
    root: List[TflApiPresentationEntitiesPlace]


class Types(RootModel[List[str]]):
    root: List[str]


class PlaceTypeTypesGetResponse(RootModel[List[TflApiPresentationEntitiesPlace]]):
    root: List[TflApiPresentationEntitiesPlace]


class PlaceIdGetResponse(RootModel[List[TflApiPresentationEntitiesPlace]]):
    root: List[TflApiPresentationEntitiesPlace]


class RoadGetResponse(RootModel[List[TflApiPresentationEntitiesRoadCorridor]]):
    root: List[TflApiPresentationEntitiesRoadCorridor]


class RoadMetaCategoriesGetResponse(RootModel[List[str]]):
    root: List[str]


class RoadMetaSeveritiesGetResponse(
    RootModel[List[TflApiPresentationEntitiesStatusSeverity]]
):
    root: List[TflApiPresentationEntitiesStatusSeverity]


class DisruptionIds(RootModel[List[str]]):
    root: List[str]


class RoadIdsGetResponse(RootModel[List[TflApiPresentationEntitiesRoadCorridor]]):
    root: List[TflApiPresentationEntitiesRoadCorridor]


class Severities(RootModel[List[str]]):
    root: List[str]


class RoadIdsStatusGetResponse(RootModel[List[TflApiPresentationEntitiesRoadCorridor]]):
    root: List[TflApiPresentationEntitiesRoadCorridor]


class SearchMetaCategoriesGetResponse(RootModel[List[str]]):
    root: List[str]


class SearchMetaSearchProvidersGetResponse(RootModel[List[str]]):
    root: List[str]


class SearchMetaSortsGetResponse(RootModel[List[str]]):
    root: List[str]


class StopTypes(RootModel[List[str]]):
    root: List[str]


class StopPointMetaCategoriesGetResponse(
    RootModel[List[TflApiPresentationEntitiesStopPointCategory]]
):
    root: List[TflApiPresentationEntitiesStopPointCategory]


class StopPointMetaModesGetResponse(RootModel[List[TflApiPresentationEntitiesMode]]):
    root: List[TflApiPresentationEntitiesMode]


class StopPointMetaStopTypesGetResponse(RootModel[List[str]]):
    root: List[str]


class StopPointModeModesDisruptionGetResponse(
    RootModel[List[TflApiPresentationEntitiesDisruptedPoint]]
):
    root: List[TflApiPresentationEntitiesDisruptedPoint]


class Lines(RootModel[List[str]]):
    root: List[str]


class LineIds(RootModel[List[str]]):
    root: List[str]


class StopPointIdsDisruptionGetResponse(
    RootModel[List[TflApiPresentationEntitiesDisruptedPoint]]
):
    root: List[TflApiPresentationEntitiesDisruptedPoint]


class ServiceTypes5(RootModel[List[ServiceType]]):
    root: List[ServiceType]


class StopPointIdRouteGetResponse(
    RootModel[List[TflApiPresentationEntitiesStopPointRouteSection]]
):
    root: List[TflApiPresentationEntitiesStopPointRouteSection]


class ServiceTypes6(RootModel[List[ServiceType]]):
    root: List[ServiceType]


class StopPointIdPlaceTypesGetResponse(
    RootModel[List[TflApiPresentationEntitiesPlace]]
):
    root: List[TflApiPresentationEntitiesPlace]


class PlaceTypes(RootModel[List[str]]):
    root: List[str]


class StopPointStopPointIdCarParksGetResponse(
    RootModel[List[TflApiPresentationEntitiesPlace]]
):
    root: List[TflApiPresentationEntitiesPlace]


class StopPointStopPointIdTaxiRanksGetResponse(
    RootModel[List[TflApiPresentationEntitiesPlace]]
):
    root: List[TflApiPresentationEntitiesPlace]


class Direction5(Enum):
    Average = 'Average'
    From = 'From'
    To = 'To'


class SystemDataSpatialDbGeography(BaseModel):
    geography: Optional[SystemDataSpatialDbGeographyWellKnownValue] = None


class TflApiPresentationEntitiesAccidentStatsAccidentDetail(BaseModel):
    borough: Optional[str] = None
    casualties: Optional[List[TflApiPresentationEntitiesAccidentStatsCasualty]] = None
    date: Optional[datetime] = None
    id: Optional[int] = None
    lat: Optional[float] = None
    location: Optional[str] = None
    lon: Optional[float] = None
    severity: Optional[str] = None
    vehicles: Optional[List[TflApiPresentationEntitiesAccidentStatsVehicle]] = None


class TflApiPresentationEntitiesArrivalDeparture(BaseModel):
    cause: Optional[str] = Field(None, description='Reason for cancellation or delay')
    departureStatus: Optional[DepartureStatus] = Field(
        None, description='Status of departure'
    )
    destinationName: Optional[str] = Field(None, description='Name of the destination')
    destinationNaptanId: Optional[str] = Field(
        None, description="Naptan Identifier for the prediction's destination"
    )
    estimatedTimeOfArrival: Optional[datetime] = Field(
        None, description='Estimated time of arrival'
    )
    estimatedTimeOfDeparture: Optional[datetime] = Field(
        None, description='Estimated time of arrival'
    )
    minutesAndSecondsToArrival: Optional[str] = Field(
        None, description='Estimated time of arrival'
    )
    minutesAndSecondsToDeparture: Optional[str] = Field(
        None, description='Estimated time of arrival'
    )
    naptanId: Optional[str] = Field(None, description='Identifier for the prediction')
    platformName: Optional[str] = Field(
        None, description='Platform name (for bus, this is the stop letter)'
    )
    scheduledTimeOfArrival: Optional[datetime] = Field(
        None, description='Estimated time of arrival'
    )
    scheduledTimeOfDeparture: Optional[datetime] = Field(
        None, description='Estimated time of arrival'
    )
    stationName: Optional[str] = Field(None, description='Station name')
    timing: Optional[TflApiPresentationEntitiesPredictionTiming] = None


class TflApiPresentationEntitiesArrivalDepartureWithLine(BaseModel):
    cause: Optional[str] = Field(None, description='Reason for cancellation or delay')
    departureStatus: Optional[DepartureStatus] = Field(
        None, description='Status of departure'
    )
    destinationName: Optional[str] = Field(None, description='Name of the destination')
    destinationNaptanId: Optional[str] = Field(
        None, description="Naptan Identifier for the prediction's destination"
    )
    estimatedTimeOfArrival: Optional[datetime] = Field(
        None, description='Estimated time of arrival'
    )
    estimatedTimeOfDeparture: Optional[datetime] = Field(
        None, description='Estimated time of arrival'
    )
    lineId: Optional[str] = Field(None, description='Train operating company name')
    lineName: Optional[str] = Field(None, description='Train operating company code')
    minutesAndSecondsToArrival: Optional[str] = Field(
        None, description='Estimated time of arrival'
    )
    minutesAndSecondsToDeparture: Optional[str] = Field(
        None, description='Estimated time of arrival'
    )
    naptanId: Optional[str] = Field(None, description='Identifier for the prediction')
    platformName: Optional[str] = Field(
        None, description='Platform name (for bus, this is the stop letter)'
    )
    scheduledTimeOfArrival: Optional[datetime] = Field(
        None, description='Estimated time of arrival'
    )
    scheduledTimeOfDeparture: Optional[datetime] = Field(
        None, description='Estimated time of arrival'
    )
    stationName: Optional[str] = Field(None, description='Station name')
    timing: Optional[TflApiPresentationEntitiesPredictionTiming] = None


class TflApiPresentationEntitiesCrowding(BaseModel):
    passengerFlows: Optional[List[TflApiPresentationEntitiesPassengerFlow]] = Field(
        None, description='Busiest times at a station (static information)'
    )
    trainLoadings: Optional[List[TflApiPresentationEntitiesTrainLoading]] = Field(
        None,
        description='Train Loading on a scale 1-6, 1 being "Very quiet" and 6 being "Exceptionally busy" (static information)',
    )


class TflApiPresentationEntitiesCycleSuperhighway(BaseModel):
    geography: Optional[SystemDataSpatialDbGeography] = None
    id: Optional[str] = Field(None, description='The Id')
    label: Optional[str] = Field(
        None, description='The long label to show on maps when zoomed in'
    )
    labelShort: Optional[str] = Field(
        None, description='The short label to show on maps'
    )
    modified: Optional[datetime] = Field(
        None, description='When the data was last updated'
    )
    routeType: Optional[RouteType] = Field(
        None,
        description='Type of cycle route e.g CycleSuperhighways, Quietways, MiniHollands etc',
    )
    segmented: Optional[bool] = Field(
        None, description='True if the route is split into segments'
    )
    status: Optional[Status] = Field(
        None, description='Cycle route status i.e Proposed, Existing etc'
    )


class TflApiPresentationEntitiesFaresFareBounds(BaseModel):
    description: Optional[str] = None
    displayName: Optional[str] = None
    displayOrder: Optional[int] = None
    from_: Optional[str] = Field(None, alias='from')
    id: Optional[int] = None
    isPopularFare: Optional[bool] = None
    isPopularTravelCard: Optional[bool] = None
    isTour: Optional[bool] = None
    messages: Optional[List[TflApiPresentationEntitiesMessage]] = None
    operator: Optional[str] = None
    routeCode: Optional[str] = None
    to: Optional[str] = None
    via: Optional[str] = None


class TflApiPresentationEntitiesFaresRecommendation(BaseModel):
    cost: Optional[str] = None
    discountCard: Optional[str] = None
    fareType: Optional[str] = None
    gettingYourTicket: Optional[List[TflApiPresentationEntitiesMessage]] = None
    id: Optional[int] = None
    keyFeatures: Optional[List[TflApiPresentationEntitiesMessage]] = None
    notes: Optional[List[TflApiPresentationEntitiesMessage]] = None
    priceComparison: Optional[str] = None
    priceDescription: Optional[str] = None
    product: Optional[str] = None
    productType: Optional[str] = None
    rank: Optional[int] = None
    recommendedTopUp: Optional[str] = None
    rule: Optional[int] = None
    singleFare: Optional[float] = None
    ticketTime: Optional[str] = None
    ticketType: Optional[str] = None
    zones: Optional[str] = None


class TflApiPresentationEntitiesFaresRecommendationResponse(BaseModel):
    recommendations: Optional[List[TflApiPresentationEntitiesFaresRecommendation]] = (
        None
    )


class TflApiPresentationEntitiesFaresTicket(BaseModel):
    cost: Optional[str] = None
    description: Optional[str] = None
    displayOrder: Optional[int] = None
    messages: Optional[List[TflApiPresentationEntitiesMessage]] = None
    mode: Optional[str] = None
    passengerType: Optional[str] = None
    ticketTime: Optional[TflApiPresentationEntitiesFaresTicketTime] = None
    ticketType: Optional[TflApiPresentationEntitiesFaresTicketType] = None


class TflApiPresentationEntitiesIdentifier(BaseModel):
    crowding: Optional[TflApiPresentationEntitiesCrowding] = None
    fullName: Optional[str] = None
    id: Optional[str] = None
    motType: Optional[str] = None
    name: Optional[str] = None
    network: Optional[str] = None
    routeType: Optional[RouteType] = None
    status: Optional[Status] = None
    type: Optional[str] = None
    uri: Optional[str] = None


class TflApiPresentationEntitiesInstructionStep(BaseModel):
    cumulativeDistance: Optional[int] = None
    cumulativeTravelTime: Optional[int] = None
    description: Optional[str] = None
    descriptionHeading: Optional[str] = None
    distance: Optional[int] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    pathAttribute: Optional[TflApiPresentationEntitiesPathAttribute] = None
    skyDirection: Optional[int] = None
    skyDirectionDescription: Optional[SkyDirectionDescription] = None
    streetName: Optional[str] = None
    trackType: Optional[TrackType] = None
    turnDirection: Optional[str] = None


class TflApiPresentationEntitiesJourneyPlannerFareTap(BaseModel):
    atcoCode: Optional[str] = None
    tapDetails: Optional[TflApiPresentationEntitiesJourneyPlannerFareTapDetails] = None


class TflApiPresentationEntitiesJourneyPlannerPath(BaseModel):
    elevation: Optional[List[TflApiCommonJourneyPlannerJpElevation]] = None
    lineString: Optional[str] = None
    stopPoints: Optional[List[TflApiPresentationEntitiesIdentifier]] = None


class TflApiPresentationEntitiesJourneyPlannerRouteOption(BaseModel):
    direction: Optional[str] = Field(
        None, description='The direction of the route, i.e. outbound or inbound.'
    )
    directions: Optional[List[str]] = None
    id: Optional[str] = Field(None, description='The Id of the route')
    lineIdentifier: Optional[TflApiPresentationEntitiesIdentifier] = None
    name: Optional[str] = Field(None, description='Name such as "72"')


class TflApiPresentationEntitiesJourneyPlannerSearchCriteria(BaseModel):
    dateTime: Optional[datetime] = None
    dateTimeType: Optional[DateTimeType] = None
    timeAdjustments: Optional[
        TflApiPresentationEntitiesJourneyPlannerTimeAdjustments
    ] = None


class TflApiPresentationEntitiesLineServiceType(BaseModel):
    lineName: Optional[str] = None
    lineSpecificServiceTypes: Optional[
        List[TflApiPresentationEntitiesLineSpecificServiceType]
    ] = None


class TflApiPresentationEntitiesMatchedStop(BaseModel):
    accessibilitySummary: Optional[str] = None
    direction: Optional[str] = None
    hasDisruption: Optional[bool] = None
    icsId: Optional[str] = None
    id: Optional[str] = None
    lat: Optional[float] = None
    lines: Optional[List[TflApiPresentationEntitiesIdentifier]] = None
    lon: Optional[float] = None
    modes: Optional[List[str]] = None
    name: Optional[str] = None
    parentId: Optional[str] = None
    routeId: Optional[int] = None
    stationId: Optional[str] = None
    status: Optional[bool] = None
    stopLetter: Optional[str] = None
    stopType: Optional[str] = None
    topMostParentId: Optional[str] = None
    towards: Optional[str] = None
    url: Optional[str] = None
    zone: Optional[str] = None


class TflApiPresentationEntitiesPeriod(BaseModel):
    frequency: Optional[TflApiPresentationEntitiesServiceFrequency] = None
    fromTime: Optional[TflApiPresentationEntitiesTwentyFourHourClockTime] = None
    toTime: Optional[TflApiPresentationEntitiesTwentyFourHourClockTime] = None
    type: Optional[Type] = None


class TflApiPresentationEntitiesPrediction(BaseModel):
    bearing: Optional[str] = Field(None, description='Bearing (between 0 to 359)')
    currentLocation: Optional[str] = Field(
        None, description='The current location of the vehicle.'
    )
    destinationName: Optional[str] = Field(None, description='Name of the destination')
    destinationNaptanId: Optional[str] = Field(
        None, description="Naptan Identifier for the prediction's destination"
    )
    direction: Optional[str] = Field(
        None, description='Direction (unified to inbound/outbound)'
    )
    expectedArrival: Optional[datetime] = Field(
        None, description='The expected arrival time of the vehicle at the stop/station'
    )
    id: Optional[str] = Field(None, description='The identitier for the prediction')
    lineId: Optional[str] = Field(None, description='Unique identifier for the Line')
    lineName: Optional[str] = Field(None, description='Line Name')
    modeName: Optional[str] = Field(
        None, description='The mode name of the station/line the prediction relates to'
    )
    naptanId: Optional[str] = Field(None, description='Identifier for the prediction')
    operationType: Optional[int] = Field(
        None,
        description='The type of the operation (1: is new or has been updated, 2: should be deleted from any client cache)',
    )
    platformName: Optional[str] = Field(
        None, description='Platform name (for bus, this is the stop letter)'
    )
    stationName: Optional[str] = Field(None, description='Station name')
    timeToLive: Optional[datetime] = Field(
        None, description='The expiry time for the prediction'
    )
    timeToStation: Optional[int] = Field(
        None, description='Prediction of the Time to station in seconds'
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='Timestamp for when the prediction was inserted/modified (source column drives what objects are broadcast on each iteration)',
    )
    timing: Optional[TflApiPresentationEntitiesPredictionTiming] = None
    towards: Optional[str] = Field(
        None,
        description='Routing information or other descriptive text about the path of the vehicle towards the destination',
    )
    vehicleId: Optional[str] = Field(
        None,
        description='The actual vehicle in transit (for train modes, the leading car of the rolling set)',
    )


class TflApiPresentationEntitiesRoadDisruptionImpactArea(BaseModel):
    endDate: Optional[datetime] = None
    endTime: Optional[str] = None
    id: Optional[int] = None
    polygon: Optional[SystemDataSpatialDbGeography] = None
    roadDisruptionId: Optional[str] = None
    startDate: Optional[datetime] = None
    startTime: Optional[str] = None


class TflApiPresentationEntitiesRoadDisruptionLine(BaseModel):
    endDate: Optional[datetime] = None
    endTime: Optional[str] = None
    id: Optional[int] = None
    isDiversion: Optional[bool] = None
    multiLineString: Optional[SystemDataSpatialDbGeography] = None
    roadDisruptionId: Optional[str] = None
    startDate: Optional[datetime] = None
    startTime: Optional[str] = None


class TflApiPresentationEntitiesRouteSearchMatch(BaseModel):
    id: Optional[str] = None
    lat: Optional[float] = None
    lineId: Optional[str] = None
    lineName: Optional[str] = None
    lineRouteSection: Optional[List[TflApiPresentationEntitiesLineRouteSection]] = None
    lon: Optional[float] = None
    matchedRouteSections: Optional[
        List[TflApiPresentationEntitiesMatchedRouteSections]
    ] = None
    matchedStops: Optional[List[TflApiPresentationEntitiesMatchedStop]] = None
    mode: Optional[str] = None
    name: Optional[str] = None
    url: Optional[str] = None


class TflApiPresentationEntitiesRouteSearchResponse(BaseModel):
    input: Optional[str] = None
    searchMatches: Optional[List[TflApiPresentationEntitiesRouteSearchMatch]] = None


class TflApiPresentationEntitiesSchedule(BaseModel):
    firstJourney: Optional[TflApiPresentationEntitiesKnownJourney] = None
    knownJourneys: Optional[List[TflApiPresentationEntitiesKnownJourney]] = None
    lastJourney: Optional[TflApiPresentationEntitiesKnownJourney] = None
    name: Optional[str] = None
    periods: Optional[List[TflApiPresentationEntitiesPeriod]] = None


class TflApiPresentationEntitiesStopPoint(BaseModel):
    accessibilitySummary: Optional[str] = None
    additionalProperties: Optional[
        List[TflApiPresentationEntitiesAdditionalProperties]
    ] = Field(
        None,
        description='A bag of additional key/value pairs with extra information about this place.',
    )
    children: Optional[List[TflApiPresentationEntitiesPlace]] = None
    childrenUrls: Optional[List[str]] = None
    commonName: Optional[str] = Field(None, description='A human readable name.')
    distance: Optional[float] = Field(
        None,
        description='The distance of the place from its search point, if this is the result\r\n            of a geographical search, otherwise zero.',
    )
    fullName: Optional[str] = None
    hubNaptanCode: Optional[str] = None
    icsCode: Optional[str] = None
    id: Optional[str] = Field(None, description='A unique identifier.')
    indicator: Optional[str] = Field(
        None, description='The indicator of the stop point e.g. "Stop K"'
    )
    individualStopId: Optional[str] = None
    lat: Optional[float] = Field(None, description='WGS84 latitude of the location.')
    lineGroup: Optional[List[TflApiPresentationEntitiesLineGroup]] = None
    lineModeGroups: Optional[List[TflApiPresentationEntitiesLineModeGroup]] = None
    lines: Optional[List[TflApiPresentationEntitiesIdentifier]] = None
    lon: Optional[float] = Field(None, description='WGS84 longitude of the location.')
    modes: Optional[List[str]] = None
    naptanId: Optional[str] = None
    naptanMode: Optional[str] = None
    placeType: Optional[str] = Field(
        None,
        description='The type of Place. See /Place/Meta/placeTypes for possible values.',
    )
    platformName: Optional[str] = None
    smsCode: Optional[str] = None
    stationNaptan: Optional[str] = None
    status: Optional[bool] = None
    stopLetter: Optional[str] = Field(
        None,
        description='The stop letter, if it could be cleansed from the Indicator e.g. "K"',
    )
    stopType: Optional[str] = None
    url: Optional[str] = Field(
        None, description='The unique location of this resource.'
    )


class TflApiPresentationEntitiesStopPointSequence(BaseModel):
    branchId: Optional[int] = Field(None, description='The id of this branch.')
    direction: Optional[str] = None
    lineId: Optional[str] = None
    lineName: Optional[str] = None
    nextBranchIds: Optional[List[int]] = Field(
        None,
        description='The ids of the next branch(es) in the sequence. Note that the next and previous branch id can be\r\n            identical in the case of a looped route e.g. the Circle line.',
    )
    prevBranchIds: Optional[List[int]] = Field(
        None,
        description='The ids of the previous branch(es) in the sequence. Note that the next and previous branch id can be\r\n            identical in the case of a looped route e.g. the Circle line.',
    )
    serviceType: Optional[ServiceType] = None
    stopPoint: Optional[List[TflApiPresentationEntitiesMatchedStop]] = None


class TflApiPresentationEntitiesStopPointsResponse(BaseModel):
    centrePoint: Optional[List[float]] = Field(
        None, description='The centre latitude/longitude of this list of StopPoints'
    )
    page: Optional[int] = Field(None, description='The index of this page')
    pageSize: Optional[int] = Field(
        None,
        description='The maximum size of the page in this response i.e. the maximum number of StopPoints',
    )
    stopPoints: Optional[List[TflApiPresentationEntitiesStopPoint]] = Field(
        None, description='Collection of stop points'
    )
    total: Optional[int] = Field(
        None, description='The total number of StopPoints available across all pages'
    )


class TflApiPresentationEntitiesStreet(BaseModel):
    closure: Optional[str] = Field(
        None,
        description='Type of road closure. Some example values:\r\n            Open = road is open, not blocked, not closed, not restricted. It maybe that the disruption has been moved out of the carriageway.\r\n            Partial Closure = road is partially blocked, closed or restricted. \r\n            Full Closure = road is fully blocked or closed.',
    )
    directions: Optional[str] = Field(
        None,
        description='The direction of the disruption on the street. Some example values:\r\n            All Directions\r\n            All Approaches\r\n            Clockwise\r\n            Anti-Clockwise\r\n            Northbound\r\n            Eastbound\r\n            Southbound\r\n            Westbound\r\n            Both Directions',
    )
    name: Optional[str] = Field(None, description='Street name')
    segments: Optional[List[TflApiPresentationEntitiesStreetSegment]] = Field(
        None,
        description='Geographic description of the sections of this street that are affected.',
    )
    sourceSystemId: Optional[int] = Field(
        None,
        description='The ID from the source system of the disruption that this street belongs to.',
    )
    sourceSystemKey: Optional[str] = Field(
        None,
        description='The key of the source system of the disruption that this street belongs to.',
    )


class TflApiPresentationEntitiesTimetableRoute(BaseModel):
    schedules: Optional[List[TflApiPresentationEntitiesSchedule]] = None
    stationIntervals: Optional[List[TflApiPresentationEntitiesStationInterval]] = None


class TflApiPresentationEntitiesTimetablesDisambiguation(BaseModel):
    disambiguationOptions: Optional[
        List[TflApiPresentationEntitiesTimetablesDisambiguationOption]
    ] = None


class AccidentStatsYearGetResponse(
    RootModel[List[TflApiPresentationEntitiesAccidentStatsAccidentDetail]]
):
    root: List[TflApiPresentationEntitiesAccidentStatsAccidentDetail]


class LineIdsArrivalsStopPointIdGetResponse(
    RootModel[List[TflApiPresentationEntitiesPrediction]]
):
    root: List[TflApiPresentationEntitiesPrediction]


class LineIdStopPointsGetResponse(RootModel[List[TflApiPresentationEntitiesStopPoint]]):
    root: List[TflApiPresentationEntitiesStopPoint]


class ModeModeArrivalsGetResponse(
    RootModel[List[TflApiPresentationEntitiesPrediction]]
):
    root: List[TflApiPresentationEntitiesPrediction]


class PlaceGetResponse(RootModel[List[TflApiPresentationEntitiesStopPoint]]):
    root: List[TflApiPresentationEntitiesStopPoint]


class StopPointServiceTypesGetResponse(
    RootModel[List[TflApiPresentationEntitiesLineServiceType]]
):
    root: List[TflApiPresentationEntitiesLineServiceType]


class StopPointTypeTypesGetResponse(
    RootModel[List[TflApiPresentationEntitiesStopPoint]]
):
    root: List[TflApiPresentationEntitiesStopPoint]


class StopPointTypeTypesPagePageGetResponse(
    RootModel[List[TflApiPresentationEntitiesStopPoint]]
):
    root: List[TflApiPresentationEntitiesStopPoint]


class StopPointIdsGetResponse(RootModel[List[TflApiPresentationEntitiesStopPoint]]):
    root: List[TflApiPresentationEntitiesStopPoint]


class StopPointIdArrivalDeparturesGetResponse(
    RootModel[List[TflApiPresentationEntitiesArrivalDeparture]]
):
    root: List[TflApiPresentationEntitiesArrivalDeparture]


class StopPointIdArrivalsGetResponse(
    RootModel[List[TflApiPresentationEntitiesPrediction]]
):
    root: List[TflApiPresentationEntitiesPrediction]


class StopPointIdCanReachOnLineLineIdGetResponse(
    RootModel[List[TflApiPresentationEntitiesStopPoint]]
):
    root: List[TflApiPresentationEntitiesStopPoint]


class StopPointIdCrowdingLineGetResponse(
    RootModel[List[TflApiPresentationEntitiesStopPoint]]
):
    root: List[TflApiPresentationEntitiesStopPoint]


class VehicleIdsArrivalsGetResponse(
    RootModel[List[TflApiPresentationEntitiesPrediction]]
):
    root: List[TflApiPresentationEntitiesPrediction]


class TflApiPresentationEntitiesFaresFareDetails(BaseModel):
    boundsId: Optional[int] = None
    contactlessPAYGOnlyFare: Optional[bool] = None
    displayName: Optional[str] = None
    displayOrder: Optional[int] = None
    endDate: Optional[datetime] = None
    from_: Optional[str] = Field(None, alias='from')
    fromStation: Optional[str] = None
    isTour: Optional[bool] = None
    messages: Optional[List[TflApiPresentationEntitiesMessage]] = None
    mode: Optional[str] = None
    operator: Optional[str] = None
    passengerType: Optional[str] = None
    routeCode: Optional[str] = None
    routeDescription: Optional[str] = None
    specialFare: Optional[bool] = None
    startDate: Optional[datetime] = None
    throughFare: Optional[bool] = None
    ticketsAvailable: Optional[List[TflApiPresentationEntitiesFaresTicket]] = None
    to: Optional[str] = None
    toStation: Optional[str] = None
    validatorInformation: Optional[str] = None
    via: Optional[str] = None


class TflApiPresentationEntitiesFaresFaresSection(BaseModel):
    header: Optional[str] = None
    index: Optional[int] = None
    journey: Optional[TflApiPresentationEntitiesFaresJourney] = None
    messages: Optional[List[TflApiPresentationEntitiesMessage]] = None
    rows: Optional[List[TflApiPresentationEntitiesFaresFareDetails]] = None


class TflApiPresentationEntitiesInstruction(BaseModel):
    detailed: Optional[str] = None
    steps: Optional[List[TflApiPresentationEntitiesInstructionStep]] = None
    summary: Optional[str] = None


class TflApiPresentationEntitiesJourneyPlannerFare(BaseModel):
    chargeLevel: Optional[str] = None
    chargeProfileName: Optional[str] = None
    cost: Optional[int] = None
    highZone: Optional[int] = None
    isHopperFare: Optional[bool] = None
    lowZone: Optional[int] = None
    offPeak: Optional[int] = None
    peak: Optional[int] = None
    taps: Optional[List[TflApiPresentationEntitiesJourneyPlannerFareTap]] = None


class TflApiPresentationEntitiesJourneyPlannerJourneyFare(BaseModel):
    caveats: Optional[List[TflApiPresentationEntitiesJourneyPlannerFareCaveat]] = None
    fares: Optional[List[TflApiPresentationEntitiesJourneyPlannerFare]] = None
    totalCost: Optional[int] = None


class TflApiPresentationEntitiesRoadDisruption(BaseModel):
    category: Optional[str] = Field(
        None,
        description='Describes the nature of disruption e.g. Traffic Incidents, Works',
    )
    comments: Optional[str] = Field(
        None,
        description='Full text of comments describing the disruption, including details of any road closures and diversions, where appropriate.',
    )
    corridorIds: Optional[List[str]] = Field(
        None, description='The Ids of affected corridors, if any.'
    )
    currentUpdate: Optional[str] = Field(
        None,
        description='Text of the most recent update from the LSTCC on the state of the\r\n             disruption, including the current traffic impact and any advice to\r\n             road users.',
    )
    currentUpdateDateTime: Optional[datetime] = Field(
        None,
        description='The time when the last CurrentUpdate description was recorded, \r\n            or null if no CurrentUpdate has been applied.',
    )
    endDateTime: Optional[datetime] = Field(
        None,
        description='The date and time on which the disruption ended. For planned disruptions, this date will have a valid value. For unplanned \r\n            disruptions in progress, this field will be omitted.',
    )
    geography: Optional[SystemDataSpatialDbGeography] = None
    geometry: Optional[SystemDataSpatialDbGeography] = None
    hasClosures: Optional[bool] = Field(
        None,
        description='True if any of the affected Streets have a "Full Closure" status, false otherwise. A RoadDisruption that has HasClosures is considered a \r\n            Severe or Serious disruption for severity filtering purposes.',
    )
    id: Optional[str] = Field(
        None, description='Unique identifier for the road disruption'
    )
    isProvisional: Optional[bool] = Field(
        None,
        description='True if the disruption is planned on a future date that is open to change',
    )
    lastModifiedTime: Optional[datetime] = Field(
        None,
        description='The date and time on which the disruption was last modified in the system. This information can reliably be used by a developer to quickly\r\n            compare two instances of the same disruption to determine if it has been changed.',
    )
    levelOfInterest: Optional[str] = Field(
        None,
        description='This describes the level of potential impact on traffic operations of the disruption. \r\n            High = e.g. a one-off disruption on a major or high profile route which will require a high level of operational attention \r\n            Medium = This is the default value \r\n            Low = e.g. a frequently occurring disruption which is well known',
    )
    linkText: Optional[str] = Field(None, description='The text of any associated link')
    linkUrl: Optional[str] = Field(None, description='The url of any associated link')
    location: Optional[str] = Field(
        None,
        description='Main road name / number (borough) or preset area name where the disruption is located. This might be useful for a map popup where space is limited.',
    )
    ordinal: Optional[int] = Field(
        None,
        description='An ordinal of the disruption based on severity, level of interest and corridor.',
    )
    point: Optional[str] = Field(
        None,
        description='Latitude and longitude (WGS84) of the centroid of the disruption, stored in a geoJSON-formatted string.',
    )
    publishEndDate: Optional[datetime] = None
    publishStartDate: Optional[datetime] = Field(
        None, description='TDM Additional properties'
    )
    recurringSchedules: Optional[
        List[TflApiPresentationEntitiesRoadDisruptionSchedule]
    ] = None
    roadDisruptionImpactAreas: Optional[
        List[TflApiPresentationEntitiesRoadDisruptionImpactArea]
    ] = None
    roadDisruptionLines: Optional[
        List[TflApiPresentationEntitiesRoadDisruptionLine]
    ] = None
    roadProject: Optional[TflApiPresentationEntitiesRoadProject] = None
    severity: Optional[str] = Field(
        None, description='A description of the severity of the disruption.'
    )
    startDateTime: Optional[datetime] = Field(
        None,
        description='The date and time which the disruption started. For a planned disruption (i.e. planned road works) this date will be in the future.\r\n            For unplanned disruptions, this will default to the date on which the disruption was first recorded, but may be adjusted by the operator.',
    )
    status: Optional[str] = Field(
        None,
        description='This describes the status of the disruption.  \r\n            Active = currently in progress \r\n            Active Long Term = currently in progress and long term\r\n            Scheduled = scheduled to start within the next 180 days\r\n            Recurring Works = planned maintenance works that follow a regular routine or pattern and whose next occurrence is to start within the next 180 days.\r\n            Recently Cleared = recently cleared in the last 24 hours\r\n            Note that the status of Scheduled or Recurring Works disruptions will change to Active when they start, and will change status again when they end.',
    )
    streets: Optional[List[TflApiPresentationEntitiesStreet]] = Field(
        None,
        description='A collection of zero or more streets affected by the disruption.',
    )
    subCategory: Optional[str] = Field(
        None,
        description='Describes the sub-category of disruption e.g. Collapsed Manhole, Abnormal Load',
    )
    timeFrame: Optional[str] = None
    url: Optional[str] = Field(None, description='URL to retrieve this road disruption')


class TflApiPresentationEntitiesRouteSectionNaptanEntrySequence(BaseModel):
    ordinal: Optional[int] = None
    stopPoint: Optional[TflApiPresentationEntitiesStopPoint] = None


class TflApiPresentationEntitiesRouteSequence(BaseModel):
    direction: Optional[str] = None
    isOutboundOnly: Optional[bool] = None
    lineId: Optional[str] = None
    lineName: Optional[str] = None
    lineStrings: Optional[List[str]] = None
    mode: Optional[str] = None
    orderedLineRoutes: Optional[List[TflApiPresentationEntitiesOrderedRoute]] = None
    stations: Optional[List[TflApiPresentationEntitiesMatchedStop]] = None
    stopPointSequences: Optional[List[TflApiPresentationEntitiesStopPointSequence]] = (
        None
    )


class TflApiPresentationEntitiesTimetable(BaseModel):
    departureStopId: Optional[str] = None
    routes: Optional[List[TflApiPresentationEntitiesTimetableRoute]] = None


class TflApiPresentationEntitiesTimetableResponse(BaseModel):
    direction: Optional[str] = None
    disambiguation: Optional[TflApiPresentationEntitiesTimetablesDisambiguation] = None
    lineId: Optional[str] = None
    lineName: Optional[str] = None
    pdfUrl: Optional[str] = None
    stations: Optional[List[TflApiPresentationEntitiesMatchedStop]] = None
    statusErrorMessage: Optional[str] = None
    stops: Optional[List[TflApiPresentationEntitiesMatchedStop]] = None
    timetable: Optional[TflApiPresentationEntitiesTimetable] = None


class RoadIdsDisruptionGetResponse(
    RootModel[List[TflApiPresentationEntitiesRoadDisruption]]
):
    root: List[TflApiPresentationEntitiesRoadDisruption]


class TflApiPresentationEntitiesDisruptedRoute(BaseModel):
    destinationName: Optional[str] = Field(
        None, description='The name of the Destination StopPoint'
    )
    direction: Optional[str] = Field(None, description='Inbound or Outbound')
    id: Optional[str] = Field(None, description='The Id of the route')
    isEntireRouteSection: Optional[bool] = Field(
        None, description='Whether this represents the entire route section'
    )
    lineId: Optional[str] = Field(None, description='The Id of the Line')
    lineString: Optional[str] = Field(
        None, description="The co-ordinates of the route's path as a geoJSON lineString"
    )
    name: Optional[str] = Field(None, description='Name such as "72"')
    originationName: Optional[str] = Field(
        None, description='The name of the Origin StopPoint'
    )
    routeCode: Optional[str] = Field(None, description='The route code')
    routeSectionNaptanEntrySequence: Optional[
        List[TflApiPresentationEntitiesRouteSectionNaptanEntrySequence]
    ] = None
    validFrom: Optional[datetime] = Field(
        None,
        description='The DateTime that the Service containing this Route is valid from.',
    )
    validTo: Optional[datetime] = Field(
        None,
        description='The DateTime that the Service containing this Route is valid until.',
    )
    via: Optional[TflApiPresentationEntitiesRouteSectionNaptanEntrySequence] = None


class TflApiPresentationEntitiesDisruption(BaseModel):
    additionalInfo: Optional[str] = Field(
        None, description='Gets or sets the additionaInfo of this disruption.'
    )
    affectedRoutes: Optional[List[TflApiPresentationEntitiesDisruptedRoute]] = Field(
        None, description='Gets or sets the routes affected by this disruption'
    )
    affectedStops: Optional[List[TflApiPresentationEntitiesStopPoint]] = Field(
        None, description='Gets or sets the stops affected by this disruption'
    )
    category: Optional[Category] = Field(
        None, description='Gets or sets the category of this dispruption.'
    )
    categoryDescription: Optional[str] = Field(
        None, description='Gets or sets the description of the category.'
    )
    closureText: Optional[str] = Field(
        None, description='Text describing the closure type'
    )
    created: Optional[datetime] = Field(
        None, description='Gets or sets the date/time when this disruption was created.'
    )
    description: Optional[str] = Field(
        None, description='Gets or sets the description of this disruption.'
    )
    lastUpdate: Optional[datetime] = Field(
        None,
        description='Gets or sets the date/time when this disruption was last updated.',
    )
    summary: Optional[str] = Field(
        None, description='Gets or sets the summary of this disruption.'
    )
    type: Optional[str] = Field(
        None, description='Gets or sets the disruption type of this dispruption.'
    )


class TflApiPresentationEntitiesJourneyPlannerLeg(BaseModel):
    arrivalPoint: Optional[TflApiPresentationEntitiesPoint] = None
    arrivalTime: Optional[datetime] = None
    departurePoint: Optional[TflApiPresentationEntitiesPoint] = None
    departureTime: Optional[datetime] = None
    disruptions: Optional[List[TflApiPresentationEntitiesDisruption]] = None
    distance: Optional[float] = None
    duration: Optional[int] = None
    hasFixedLocations: Optional[bool] = None
    instruction: Optional[TflApiPresentationEntitiesInstruction] = None
    interChangeDuration: Optional[str] = None
    interChangePosition: Optional[str] = None
    isDisrupted: Optional[bool] = None
    mode: Optional[TflApiPresentationEntitiesIdentifier] = None
    obstacles: Optional[List[TflApiPresentationEntitiesJourneyPlannerObstacle]] = None
    path: Optional[TflApiPresentationEntitiesJourneyPlannerPath] = None
    plannedWorks: Optional[
        List[TflApiPresentationEntitiesJourneyPlannerPlannedWork]
    ] = None
    routeOptions: Optional[
        List[TflApiPresentationEntitiesJourneyPlannerRouteOption]
    ] = None
    scheduledArrivalTime: Optional[datetime] = None
    scheduledDepartureTime: Optional[datetime] = None
    speed: Optional[str] = None


class TflApiPresentationEntitiesLineStatus(BaseModel):
    created: Optional[datetime] = None
    disruption: Optional[TflApiPresentationEntitiesDisruption] = None
    id: Optional[int] = None
    lineId: Optional[str] = None
    modified: Optional[datetime] = None
    reason: Optional[str] = None
    statusSeverity: Optional[int] = None
    statusSeverityDescription: Optional[str] = None
    validityPeriods: Optional[List[TflApiPresentationEntitiesValidityPeriod]] = None


class LineModeModesDisruptionGetResponse(
    RootModel[List[TflApiPresentationEntitiesDisruption]]
):
    root: List[TflApiPresentationEntitiesDisruption]


class LineIdsDisruptionGetResponse(
    RootModel[List[TflApiPresentationEntitiesDisruption]]
):
    root: List[TflApiPresentationEntitiesDisruption]


class TflApiPresentationEntitiesJourneyPlannerJourney(BaseModel):
    arrivalDateTime: Optional[datetime] = None
    duration: Optional[int] = None
    fare: Optional[TflApiPresentationEntitiesJourneyPlannerJourneyFare] = None
    legs: Optional[List[TflApiPresentationEntitiesJourneyPlannerLeg]] = None
    startDateTime: Optional[datetime] = None


class TflApiPresentationEntitiesLine(BaseModel):
    created: Optional[datetime] = None
    crowding: Optional[TflApiPresentationEntitiesCrowding] = None
    disruptions: Optional[List[TflApiPresentationEntitiesDisruption]] = None
    id: Optional[str] = None
    lineStatuses: Optional[List[TflApiPresentationEntitiesLineStatus]] = None
    modeName: Optional[str] = None
    modified: Optional[datetime] = None
    name: Optional[str] = None
    routeSections: Optional[List[TflApiPresentationEntitiesMatchedRoute]] = None
    serviceTypes: Optional[List[TflApiPresentationEntitiesLineServiceTypeInfo]] = None


class LineModeModesGetResponse(RootModel[List[TflApiPresentationEntitiesLine]]):
    root: List[TflApiPresentationEntitiesLine]


class LineModeModesRouteGetResponse(RootModel[List[TflApiPresentationEntitiesLine]]):
    root: List[TflApiPresentationEntitiesLine]


class LineModeModesStatusGetResponse(RootModel[List[TflApiPresentationEntitiesLine]]):
    root: List[TflApiPresentationEntitiesLine]


class LineRouteGetResponse(RootModel[List[TflApiPresentationEntitiesLine]]):
    root: List[TflApiPresentationEntitiesLine]


class LineStatusSeverityGetResponse(RootModel[List[TflApiPresentationEntitiesLine]]):
    root: List[TflApiPresentationEntitiesLine]


class LineIdsGetResponse(RootModel[List[TflApiPresentationEntitiesLine]]):
    root: List[TflApiPresentationEntitiesLine]


class LineIdsRouteGetResponse(RootModel[List[TflApiPresentationEntitiesLine]]):
    root: List[TflApiPresentationEntitiesLine]


class LineIdsStatusGetResponse(RootModel[List[TflApiPresentationEntitiesLine]]):
    root: List[TflApiPresentationEntitiesLine]


class LineIdsStatusStartDateToEndDateGetResponse(
    RootModel[List[TflApiPresentationEntitiesLine]]
):
    root: List[TflApiPresentationEntitiesLine]


class TflApiPresentationEntitiesJourneyPlannerItineraryResult(BaseModel):
    cycleHireDockingStationData: Optional[
        TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData
    ] = None
    journeyVector: Optional[TflApiPresentationEntitiesJourneyPlannerJourneyVector] = (
        None
    )
    journeys: Optional[List[TflApiPresentationEntitiesJourneyPlannerJourney]] = None
    lines: Optional[List[TflApiPresentationEntitiesLine]] = None
    recommendedMaxAgeMinutes: Optional[int] = None
    searchCriteria: Optional[TflApiPresentationEntitiesJourneyPlannerSearchCriteria] = (
        None
    )
    stopMessages: Optional[List[str]] = None


TflApiPresentationEntitiesPlace.model_rebuild()
